docs/en/_static/css/readthedocs.css, docs/en/conf.py, docs/zh_cn/_static/css/readthedocs.css, docs/zh_cn/conf.py
=> [Fix] fix docs

README.md
=> [Docs] fix readme

README.md, README_zh-CN.md
=> [Fix] fix license

README.md, README_zh-CN.md
=> [Fix] fix readme

README.md, README_zh-CN.md
=> [Docs] Update readme

opencompass/tasks/openicl_infer.py
=> [Fix] Fix OpenICLInferTask

opencompass/openicl/icl_inferencer/icl_clp_inferencer.py
Fix clp inferencer error for huggingface models
**Before PR**:
**After PR**:
=> [Fix] fix clp inferencer

requirements.txt, run.py
=> [Fix] Fix errors caused by MMEngine 0.8.1

opencompass/openicl/icl_evaluator/icl_toxic_evaluator.py
PerspectiveAPI quota and speed is fluctuating, need an experiment arguments to speed up or slow down
1. Add `bs` for `ToxicEvaluator`. 
**Before PR**:
**After PR**:
=> [Feat] add bs for perspective api eval

docs/en/OmniMMBench.md
=> [Feature]add omnibenchmark readme

docs/en/MMBench.md
=> [Fix]: Refine name

README.md, docs/en/MMBench.md
=> [Feature]: Add MMBench

README.md, README_zh-CN.md
=> [Doc] add discord and wechat link

docs/en/user_guides/experimentation.md, docs/zh_cn/user_guides/experimentation.md, run.py
I want to check what tasks will be launched without actually running them.
=> [Feature] Add --dry-run option

docs/en/user_guides/evaluation.md, docs/zh_cn/user_guides/evaluation.md
=> [Docs] Update evaluation doc

configs/datasets/FewCLUE_chid/FewCLUE_chid_ppl_8f2872.py, opencompass/datasets/GaokaoBench.py, opencompass/datasets/agieval/agieval.py, opencompass/datasets/mmlu.py, opencompass/tasks/openicl_eval.py, opencompass/tasks/openicl_infer.py
* Open cn datasets with `encoding='utf-8'`.
* Fix chid ppl config error 
* Add more `logger.info`
=> Add logger info and remove dataset bugs

configs/models/hf_baichuan_13b_base.py, configs/models/hf_baichuan_13b_chat.py
=> [Feature] Add baichuan13b model configs

configs/eval_llama_7b.py
fix `configs/eval_llama_7b.py`
=> [FIx] fix `configs/eval_llama_7b.py`

.codespellrc, .github/workflows/lint.yml, docs/en/MMBench.md, opencompass/openicl/icl_evaluator/icl_toxic_evaluator.py
=> [Fix] Fix CI

configs/models/hf_falcon_40b.py
Support falcon 40b
**Before PR**:
**After PR**:
=> [Feat] add falcon-40b

configs/datasets/tydiqa/tydiqa_gen.py, configs/datasets/tydiqa/tydiqa_gen_978d2a.py, opencompass/datasets/__init__.py, opencompass/datasets/tydiqa.py
=> [Feature]  Add TydiQA-goldp task

opencompass/models/huggingface.py
Support loading PEFT adapter for HuggingFace model
Add argument `peft_path` for `HuggingFace` class
**Before PR**:
**After PR**:
=> [Feature] Support load PEFT adapter for HuggingFace model

configs/datasets/cvalues/cvalues_responsibility_gen.py, configs/datasets/cvalues/cvalues_responsibility_gen_4aec9f.py, opencompass/datasets/__init__.py, opencompass/datasets/cvalues.py
Support CValues Responsibility dataset
**Before PR**:
**After PR**:
=> [Feat] Support CValues Responsibility dataset

docs/en/MMBench.md
1. Fix typos in pseudo code
2. Fix the mona lisa image
=> [Fix] MMBench Doc Fix

configs/datasets/collections/chat_medium.py, configs/datasets/collections/chat_small.py, configs/datasets/crowspairs/crowspairs_gen.py, configs/datasets/crowspairs/crowspairs_gen_21f7cb.py, opencompass/datasets/crowspairs.py
Chat model does not always choose between A and B, try to evaluation as accurate as possible
Add additional postprocessor and evaluator.
**Before PR**:
**After PR**:
=> [Refactor] Update crows-pairs evaluation

docs/en/prompt/meta_template.md, docs/zh_cn/prompt/meta_template.md, docs/zh_cn/prompt/prompt_template.md
=> [Docs] Prompt docs

README.md, README_zh-CN.md
Fix the readme refer to #107 
**Before PR**:
**After PR**:
=> [Doc] Update Readme and Fix failed links

README.md, README_zh-CN.md
1. Added a Twitter link~
2. Updated the tweet link a bit, now users only have to scan the code once, before they had to scan it twice
=> Doc: add twitter link

.github/ISSUE_TEMPLATE/1_bug-report.yml, .github/ISSUE_TEMPLATE/2_feature-request.yml, .github/ISSUE_TEMPLATE/3_bug-report_zh.yml, .github/ISSUE_TEMPLATE/4_feature-request_zh.yml
=> [Docs] Update issue templates for proper guidance to discussions

.pre-commit-config-zh-cn.yaml, opencompass/openicl/icl_inferencer/icl_clp_inferencer.py, opencompass/utils/lark.py, requirements.txt
1. Add precommit hook config for the ease of access from China
2. make lark.py a standalone script 
3. Cleaned up some internal code
4. update requirements.txt
=> [Feature] Several enhancements

README.md, README_zh-CN.md
=> [Doc] update acknowledgements

opencompass/openicl/icl_evaluator/icl_hf_evaluator.py
Refine PR #122, set random seed in function `score` rather than `__init__`
=> [Refine] Refine PR #122

README.md, README_zh-CN.md
=> [Doc] Update Readme

configs/multimodal/instructblip/instructblip-mmbench.py, configs/multimodal/minigpt_4/minigpt_4_7b_mmbench.py, opencompass/tasks/mm_infer.py
=> [Feature]: Add mm suport for local runner

configs/eval_gpt3.5.py, opencompass/models/openai_api.py
=> Calculate max_out_len without hard code for OpenAI model

configs/eval_internlm_chat_7b_turbomind.py, configs/models/hf_internlm_chat_7b.py, docs/en/advanced_guides/evaluation_turbomind.md, docs/en/index.rst, docs/zh_cn/advanced_guides/evaluation_turbomind.md, docs/zh_cn/index.rst, opencompass/models/turbomind.py
=> [Feature] Support turbomind

opencompass/runners/local.py, run.py
=> [Feature] Support CUDA_VISIBLE_DEVICES and multiple tasks on one GPU

.github/ISSUE_TEMPLATE/1_bug-report.yml, .github/ISSUE_TEMPLATE/3_bug-report_zh.yml
Preview:
https://github.com/gaotongxiao/opencompass/issues/new?assignees=&labels=bug&projects=&template=1_bug-report.yml&title=%5BBug%5D+
https://github.com/gaotongxiao/opencompass/issues/new?assignees=&labels=bug&projects=&template=3_bug-report_zh.yml&title=%5BBug%5D+
=> [Docs] Enhance issue template

opencompass/models/openai_api.py
=> Skip invalid keys to avoid requesting API

README.md, README_zh-CN.md, docs/en/advanced_guides/evaluation_turbomind.md, docs/zh_cn/advanced_guides/evaluation_turbomind.md
=> [Feature] update news

opencompass/utils/logging.py
=> [Feature] Support filtering specified levels message

configs/datasets/ARC_c/ARC_c_gen_1e0de5.py, configs/datasets/ARC_e/ARC_e_gen_1e0de5.py, configs/datasets/SuperGLUE_AX_b/SuperGLUE_AX_b_gen_4dfefa.py, configs/datasets/SuperGLUE_AX_g/SuperGLUE_AX_g_gen_68aac7.py, configs/datasets/SuperGLUE_CB/SuperGLUE_CB_gen_854c6c.py, configs/datasets/SuperGLUE_COPA/SuperGLUE_COPA_gen_91ca53.py, configs/datasets/SuperGLUE_MultiRC/SuperGLUE_MultiRC_gen_27071f.py, configs/datasets/SuperGLUE_RTE/SuperGLUE_RTE_gen_68aac7.py, configs/datasets/agieval/agieval_gen_397d81.py, configs/datasets/hellaswag/hellaswag_gen_6faab5.py, configs/datasets/obqa/obqa_gen_9069e4.py, configs/datasets/piqa/piqa_gen_1194eb.py, configs/datasets/race/race_gen_69ee4f.py, configs/datasets/storycloze/storycloze_gen_7f656a.py, configs/datasets/winogrande/winogrande_gen_a9ede5.py, opencompass/utils/text_postprocessors.py
=> [Feat] update postprocessor to get first option more accurately

configs/datasets/collections/chat_medium.py, opencompass/tasks/openicl_eval.py, opencompass/utils/text_postprocessors.py
=> [Fix] fix bug for postprocessor

configs/multimodal/minigpt_4/minigpt_4_7b_coco_caption.py, configs/multimodal/minigpt_4/minigpt_4_7b_mmbench.py, configs/multimodal/minigpt_4/minigpt_4_7b_scienceqa.py, configs/multimodal/minigpt_4/minigpt_4_7b_vqav2.py, configs/multimodal/minigpt_4/minigpt_4_7b_vsr.py, configs/multimodal/tasks.py, opencompass/multimodal/models/minigpt_4/__init__.py, opencompass/multimodal/models/minigpt_4/minigpt_4.py, opencompass/multimodal/models/minigpt_4/post_processor.py, opencompass/multimodal/models/minigpt_4/prompt_constructor.py
=> [Feature]: Add other public datasets

docs/zh_cn/conf.py
=> [Doc] Update Navigation bar language type

configs/multimodal/minigpt_4/minigpt_4_7b_flickr30k.py, configs/multimodal/minigpt_4/minigpt_4_7b_gqa.py, configs/multimodal/minigpt_4/minigpt_4_7b_ocr-vqa.py, configs/multimodal/minigpt_4/minigpt_4_7b_ok-vqa.py, configs/multimodal/minigpt_4/minigpt_4_7b_textvqa.py, configs/multimodal/minigpt_4/minigpt_4_7b_vizwiz.py
=> [Feature]: Add other public datasets config

configs/multimodal/minigpt_4/README.md
=> [Feature]: Add launch script

opencompass/models/openai_api.py
=> [Fix] bin_trim

opencompass/runners/local.py
see https://github.com/InternLM/opencompass/issues/179
=> [Fix] fix local runner debug

README.md, README_zh-CN.md
=> [Doc]update news

configs/multimodal/instructblip/README.md, configs/multimodal/instructblip/instructblip-mmbench.py, configs/multimodal/instructblip/instructblip_mmbench.py, opencompass/multimodal/models/instructblip/__init__.py, opencompass/multimodal/models/instructblip/blip2_vicuna_instruct.py, opencompass/multimodal/models/instructblip/post_processor.py, opencompass/multimodal/models/instructblip/prompt_constructor.py
=> [Refactor] Refactor instructblip

opencompass/models/huggingface.py
Fix bugs for PeftModel generate
opencompass/models/huggingface.py
**Before PR**:
**After PR**:
=> [Fix] Fix bugs for PeftModel generate

configs/multimodal/openflamingo/README.md, configs/multimodal/openflamingo/openflamingo_mmbench.py, configs/multimodal/tasks.py, opencompass/multimodal/models/__init__.py, opencompass/multimodal/models/openflamingo/__init__.py, opencompass/multimodal/models/openflamingo/openflamingo.py
=> [Feature]: Add Flamingo

configs/eval_claude.py, configs/eval_claude2.py, opencompass/models/claude_api.py
=> [Feature] Add Claude support

configs/multimodal/llava/llava_7b_coco_caption.py, configs/multimodal/llava/llava_7b_flickr30k.py, configs/multimodal/llava/llava_7b_gqa.py, configs/multimodal/llava/llava_7b_mmbench.py, configs/multimodal/llava/llava_7b_ocr_vqa.py, configs/multimodal/llava/llava_7b_ok_vqa.py, configs/multimodal/llava/llava_7b_scienceqa.py, configs/multimodal/llava/llava_7b_textvqa.py, configs/multimodal/llava/llava_7b_vizwiz.py, configs/multimodal/llava/llava_7b_vqav2.py, configs/multimodal/llava/llava_7b_vsr.py, configs/multimodal/visualglm/visualglm_6b_coco_caption.py, configs/multimodal/visualglm/visualglm_6b_flickr30k.py, configs/multimodal/visualglm/visualglm_6b_gqa.py, configs/multimodal/visualglm/visualglm_6b_ocr_vqa.py, configs/multimodal/visualglm/visualglm_6b_ok_vqa.py, configs/multimodal/visualglm/visualglm_6b_scienceqa.py, configs/multimodal/visualglm/visualglm_6b_textvqa.py, configs/multimodal/visualglm/visualglm_6b_vizwiz.py, configs/multimodal/visualglm/visualglm_6b_vqav2.py, configs/multimodal/visualglm/visualglm_6b_vsr.py, opencompass/multimodal/models/llava/__init__.py, opencompass/multimodal/models/llava/llava.py, opencompass/multimodal/models/llava/post_processor.py, opencompass/multimodal/models/llava/prompt_constructor.py, opencompass/multimodal/models/visualglm/__init__.py, opencompass/multimodal/models/visualglm/post_processor.py, opencompass/multimodal/models/visualglm/prompt_constructor.py, opencompass/multimodal/models/visualglm/visualglm.py
=> [Feat] Support public dataset of visualglm and llava.

configs/datasets/collections/base_medium_llama.py
Closes https://github.com/InternLM/opencompass/issues/257
=> [Fix] wrong path in dataset collections

requirements/docs.txt
=> [Docs] Update doc theme 

configs/models/codellama/hf_codellama_13b.py, configs/models/codellama/hf_codellama_13b_instruct.py, configs/models/codellama/hf_codellama_13b_python.py, configs/models/codellama/hf_codellama_34b.py, configs/models/codellama/hf_codellama_34b_instruct.py, configs/models/codellama/hf_codellama_34b_python.py, configs/models/codellama/hf_codellama_7b.py, configs/models/codellama/hf_codellama_7b_instruct.py, configs/models/codellama/hf_codellama_7b_python.py, opencompass/datasets/humanevalx.py, tools/collect_code_preds.py
=> [Feat] support codellama and preds collection tools

opencompass/models/huggingface.py, opencompass/models/intern_model.py, opencompass/models/llama2.py, opencompass/openicl/icl_inferencer/icl_clp_inferencer.py, opencompass/utils/run.py, run.py
link to https://github.com/InternLM/opencompass/issues/284
=> [Fix] Fix when missing both pad and eos token

docs/en/MMBench.md
Fix minor problem in the doc
If this PR introduces a new feature, it is better to list some use cases here and update the …
=> [Doc] Update MMBench.md

opencompass/multimodal/models/__init__.py
=> [Enhance] Add import check of multimodal

opencompass/utils/logging.py
Supress the warning like this:
**Before PR**:
**After PR**:
=> [Enhance] Supress warning raised by get_logger

opencompass/partitioners/size.py, run.py
=> [Enhancement] Increase default task size

docs/en/advanced_guides/code_eval_service.md, docs/zh_cn/advanced_guides/code_eval_service.md
=> [Docs] update code evaluator docs

configs/multimodal/qwen/qwen_7b_mmbench.py, configs/multimodal/qwen/qwenvl_base_7b_mmbench.py, configs/multimodal/qwen/qwenvl_chat_7b_mmbench.py, opencompass/multimodal/models/__init__.py, opencompass/multimodal/models/qwen/__init__.py, opencompass/multimodal/models/qwen/generation_utils.py, opencompass/multimodal/models/qwen/post_processor.py, opencompass/multimodal/models/qwen/prompt_constructor.py, opencompass/multimodal/models/qwen/qwen.py
=> [Feat] Support Qwen-VL-Chat on MMBench.

configs/models/claude2.py, opencompass/models/claude_api/postprocessors.py
=> [Feature] Update claude2 postprocessor

.github/ISSUE_TEMPLATE/1_bug-report.yml, .github/ISSUE_TEMPLATE/2_feature-request.yml, .github/ISSUE_TEMPLATE/3_bug-report_zh.yml, .github/ISSUE_TEMPLATE/4_feature-request_zh.yml, .github/ISSUE_TEMPLATE/config.yml, README.md, README_zh-CN.md, docs/en/advanced_guides/code_eval_service.md, docs/en/conf.py, docs/en/get_started.md, docs/en/notes/contribution_guide.md, docs/en/prompt/chain_of_thought.md, docs/en/user_guides/config.md, docs/en/user_guides/metrics.md, docs/zh_cn/advanced_guides/code_eval_service.md, docs/zh_cn/conf.py, docs/zh_cn/get_started.md, docs/zh_cn/notes/contribution_guide.md, docs/zh_cn/prompt/chain_of_thought.md, docs/zh_cn/user_guides/config.md, docs/zh_cn/user_guides/metrics.md
=> [Feat] Update URL

configs/multimodal/instructblip/instructblip_coco_caption.py, configs/multimodal/instructblip/instructblip_flickr30k.py, configs/multimodal/instructblip/instructblip_gqa.py, configs/multimodal/instructblip/instructblip_ocr_vqa.py, configs/multimodal/instructblip/instructblip_ok_vqa.py, configs/multimodal/instructblip/instructblip_scienceqa.py, configs/multimodal/instructblip/instructblip_textvqa.py, configs/multimodal/instructblip/instructblip_vizwiz.py, configs/multimodal/instructblip/instructblip_vqav2.py, configs/multimodal/instructblip/instructblip_vsr.py, opencompass/multimodal/models/instructblip/__init__.py, opencompass/multimodal/models/instructblip/blip2_vicuna_instruct.py, opencompass/multimodal/models/instructblip/post_processor.py, opencompass/multimodal/models/instructblip/prompt_constructor.py
=> [Feature] Add open source dataset eval config of instruct-blip

README.md, README_zh-CN.md
=> [Doc] Update News

.github/workflows/publish-to-pypi.yml, setup.py
=> [CI] Publish to Pypi

docs/en/faq.md, docs/en/get_started.md, docs/en/index.rst, docs/zh_cn/conf.py, docs/zh_cn/cp_origin_docs.sh, docs/zh_cn/get_started.md, docs/zh_cn/index.rst
1. Add FAQ.md, and its reference in Get Started
2. Add a script which automatically copies missing docs from English version to Chinese version - in order to reduce some future maintenance effort
=> [Docs] Add FAQ

configs/multimodal/instructblip/instructblip_scienceqa.py, configs/multimodal/llava/llava_7b_scienceqa.py, configs/multimodal/minigpt_4/minigpt_4_7b_scienceqa.py, configs/multimodal/visualglm/visualglm_6b_scienceqa.py
=> [Fix]: Add has_image to scienceqa

configs/datasets/ds1000/ds1000_gen_cbc84f.py, opencompass/datasets/__init__.py, opencompass/datasets/ds1000.py
=> [Feat] support ds1000 dataset

configs/datasets/truthfulqa/truthfulqa_gen_1e7d8d.py, configs/datasets/truthfulqa/truthfulqa_gen_5ddc62.py, opencompass/datasets/truthfulqa.py
for #404 
**Before PR**:
**After PR**:
=> [Feat] refine docs and codes for more user guides

README.md, README_zh-CN.md, docs/en/notes/news.md, docs/zh_cn/notes/news.md
=> [Docs] Add intro figure to README

opencompass/utils/summarizer.py
I noticed the `Summarizer` was unable to properly log debug information. After checking the source code, it looks like there may be a bug.
Just one line needs changing. Modifying `self.debug` to `self.logger.debug` in file `opencompass/utils/summarizer.py` will allow the logger to output the logs correctly. 
**Before PR**:
**After PR**:
=> [fix] summarizer debug logger

opencompass/models/base.py, opencompass/models/base_api.py, opencompass/openicl/icl_inferencer/icl_attack_inferencer.py, opencompass/openicl/icl_inferencer/icl_base_inferencer.py, opencompass/openicl/icl_inferencer/icl_clp_inferencer.py, opencompass/openicl/icl_inferencer/icl_gen_inferencer.py, opencompass/openicl/icl_inferencer/icl_ppl_inferencer.py, opencompass/openicl/icl_inferencer/icl_sc_inferencer.py, opencompass/openicl/icl_inferencer/icl_tot_inferencer.py
=> [Feature] Log gold answer in prediction output

opencompass/partitioners/base.py
This bug is known to break all the tasks.
=> [Fix] P0: errors in keep keys

configs/datasets/GLUE_QQP/GLUE_QQP_ppl.py, configs/datasets/GLUE_QQP/GLUE_QQP_ppl_250d00.py
=> [SIG] add GLUE QQP dataset

configs/datasets/GLUE_MRPC/GLUE_MRPC_ppl.py, configs/datasets/GLUE_MRPC/GLUE_MRPC_ppl_96564c.py
=> [SIG] add GLUE_MRPC  dataset

README.md, README_zh-CN.md
=> [Docs] Fix dead links in readme

.codespellrc, configs/datasets/subjectivity_cmp/subjectivity_cmp.py, configs/subjective_infer.py, configs/summarizers/example.py, configs/summarizers/leaderboard.py, configs/summarizers/leval.py, configs/summarizers/longbench.py, configs/summarizers/medium.py, configs/summarizers/small.py, configs/summarizers/subjective.py, opencompass/datasets/lmeval.py, opencompass/datasets/subjectivity_cmp.py, opencompass/openicl/icl_evaluator/lm_evaluator.py, opencompass/partitioners/sub_naive.py, opencompass/registry.py, opencompass/summarizers/__init__.py, opencompass/summarizers/default.py, opencompass/summarizers/subjective.py, opencompass/tasks/openicl_eval.py, opencompass/tasks/subjective_eval.py, opencompass/utils/__init__.py, opencompass/utils/abbr.py, requirements/runtime.txt, run.py
same as in https://github.com/open-compass/opencompass/pull/468, follow the code reviews.
=> [Sync] Add subjective evaluation

configs/datasets/MathBench/mathbench_gen.py, configs/datasets/MathBench/mathbench_gen_86de1c.py, opencompass/datasets/__init__.py, opencompass/datasets/mathbench.py, opencompass/openicl/icl_evaluator/__init__.py, opencompass/openicl/icl_evaluator/icl_circular_evaluator.py
=> [Feature] Add mathbench dataset and circular evaluator

opencompass/utils/run.py
Average scores of ceval, mmlu, etc. can be shown via command like `python3 run.py --datasets ceval_ppl --models hf_internlm_7b`
=> [Feat] use example summarizer by default

opencompass/runners/local.py, opencompass/tasks/openicl_eval.py, opencompass/tasks/openicl_infer.py, opencompass/utils/menu.py
=> [Feat] support local runner for windows

configs/datasets/SuperGLUE_WSC/SuperGLUE_WSC_gen.py, configs/datasets/SuperGLUE_WSC/SuperGLUE_WSC_gen_7902a7.py, configs/datasets/SuperGLUE_WSC/SuperGLUE_WSC_gen_fe4bf3.py, configs/datasets/SuperGLUE_WSC/SuperGLUE_WSC_ppl.py, configs/datasets/SuperGLUE_WSC/SuperGLUE_WSC_ppl_1c4a90.py, configs/datasets/collections/chat_medium.py, configs/datasets/collections/chat_small.py
Fix the typos in the WSC task prompt, in the internal model test, the impact of this modification is about ±3%
=> fix typo in WSC prompt

opencompass/runners/local.py
=> [Fix] fix local debug mode not restrict the resources

README.md
I have noticed one enhancement in **README** inside section "**Introduction**"
"**each experiment, support**"  should be "**each experiment, and support**"
Screenshot-
=> Update README.md - one enhancement.

configs/multimodal/llava/README.md, configs/multimodal/minigpt_4/README.md
I have fixed typo `environement -> environment` in markdown files. I kindly request the repository maintainers to review and merge it. Thanks! :heart:
If this PR introduces a new …
=> docs: fix typos in markdown files

opencompass/multimodal/models/minigpt_4/minigpt_4.py
=> [Feature]: To be compatible with the latest version of MiniGPT-4

opencompass/models/__init__.py, opencompass/models/xunfei_api.py
use following config to speed up, more details refer to https://github.com/open-compass/opencompass/pull/497
```python
infer = dict(
partitioner=dict(type=NaivePartitioner),
runner=dict(
type=LocalAPIRunner,
max_num_workers=4,
concurrent_users=10,
task=dict(type=OpenICLInferTask)),
)
```
If this PR introduces a new feature, it is better to list some use cases here and update the …
=> [Feat] support xunfei api model

opencompass/models/minimax_api.py, opencompass/models/xunfei_api.py, opencompass/models/zhipuai_api.py
=> [Fix] fix registry error with internal

opencompass/datasets/cibench.py, requirements/extra.txt
=> [Fix] fix unnecessary import and update requirements

configs/eval_minimax.py, opencompass/runners/local_api.py
=> [Fix] fix log re-direct

requirements/api.txt
=> [Doc] Update api.txt

opencompass/models/xunfei_api.py, opencompass/tasks/mm_infer.py
=> [Feature] Update xunfei api

configs/datasets/MathBench/mathbench_gen.py, configs/datasets/MathBench/mathbench_gen_10da90.py, opencompass/models/xunfei_api.py
=> [Feature] Update mathbench

configs/datasets/tydiqa/tydiqa_gen_978d2a.py
I found a wrong word spell in OpenCompass, it will impact on the naming of the output file, and there may be interference during secondary development.
Correct the word
**Before PR**:
**After PR**:
=> update word spell

configs/datasets/MathBench/mathbench_gen_ccd638.py, opencompass/datasets/mathbench.py
=> [Feature] Add arithmetic to mathbench

configs/eval_alaya.py, configs/models/alaya/alaya.py, opencompass/models/__init__.py, opencompass/models/alaya.py, requirements/alaya.txt, requirements/runtime.txt
Add support for DataCanvas Alaya LM
Add Class AlayaLM to support Alaya model inference.
Set 5 benchmarks to evaluate in eval_alaya.py.
No breaking.
**Before PR**:
**After PR**:
=> Add support for DataCanvas Alaya LM

configs/eval_lightllm.py, docs/en/advanced_guides/evaluation_lightllm.md, docs/en/index.rst, docs/zh_cn/advanced_guides/evaluation_lightllm.md, docs/zh_cn/index.rst, opencompass/models/__init__.py, opencompass/models/lightllm_api.py
To support lightllm api.
lightllm: https://github.com/ModelTC/lightllm
Add LightllmApi in lightllm_api.py.
Add a config file named eval_lightllm.py.
Do not introduce changes that break the backward compatibility of the downstream repositories.
`
git clone https://github.com/ModelTC/lightllm.git
cd lightllm
python -m lightllm.server.api_server --model_dir /path/llama-7b --tp 1 --max_total_token_num 121060 --tokenizer_mode auto
`
`
cd opencompass
python run.py configs/eval_lightllm.py
`
**Before PR**:
**After PR**:
=> [Feature] Support Lightllm api

opencompass/models/base.py, opencompass/models/base_api.py, opencompass/models/lightllm_api.py, opencompass/models/turbomind.py, opencompass/models/turbomind_tis.py, opencompass/openicl/icl_inferencer/icl_gen_inferencer.py
=> [Bug] Update api with generation_kargs

docs/en/advanced_guides/code_eval_service.md, docs/en/index.rst, docs/zh_cn/advanced_guides/code_eval_service.md, docs/zh_cn/index.rst
=> [Docs] update ds1000 code eval docs

README.md, README_zh-CN.md, docs/en/get_started/installation.md, docs/en/notes/news.md, docs/zh_cn/get_started/installation.md, docs/zh_cn/notes/news.md, requirements/runtime.txt
- Use `mmengine-lite` to avoid the dependency of `cv2`
- Update the News/CPU-only installation instruction
If this PR …
=> [Doc] Update README and requirements.

opencompass/tasks/openicl_eval.py
Fix nested list prediction collection error
**Before PR**:
**After PR**:
=> [Bug] fix icl eval with nested list

README.md, README_zh-CN.md
=> fix typo in README

configs/api_examples/eval_api_zhipu.py, opencompass/utils/text_postprocessors.py
=> [Feat] support zhipu post process

requirements/runtime.txt
`colossalai` is not used in github and will cause installation error in Windows
**Before PR**:
**After PR**:
=> [Fix] remove colossalai dependency

configs/datasets/wikibench/wikibench_gen.py, configs/datasets/wikibench/wikibench_gen_f96ece.py, opencompass/datasets/__init__.py, opencompass/datasets/wikibench.py
=> [Feature] Add wikibench dataset

opencompass/summarizers/default.py
=> [Fix] fix bug on standart_deviation summarizer

README.md, README_zh-CN.md, configs/api_examples/eval_api_360.py, configs/api_examples/eval_api_baichuan.py, configs/api_examples/eval_api_baidu.py, configs/api_examples/eval_api_bytedance.py, configs/api_examples/eval_api_moonshot.py, configs/eval_mixtral_8x7b.py, configs/models/mixtral/mixtral_8x7b_32k.py, opencompass/models/__init__.py, opencompass/models/ai360_api.py, opencompass/models/baichuan_api.py, opencompass/models/baidu_api.py, opencompass/models/bytedance_api.py, opencompass/models/mixtral.py, opencompass/models/moonshot_api.py
=> [Enhancement] Update API Interface

.github/workflows/pr-stage-check.yml, requirements/runtime.txt
This is a demo version of pr merge ci test.
which run in Python 3.10 on following environment
- windows torch 2.0 cpu
- ubuntu 22.04 torch 2.0 cpu
- ubuntu 22.04 torch 2.0 gpu
No actual inference is tested due to the resources limitation in current version.
**Before PR**: …
=> [Feat] support pr merge test ci

opencompass/datasets/humaneval.py
=> [Feature] enhance the ability of humaneval_postprocess

opencompass/lagent/actions/ipython_interpreter.py
=> [Docs] fix docstring

configs/subjective_score.py, opencompass/partitioners/sub_naive.py
=> fixed small problem of new version subject evaluation

configs/datasets/subjective_cmp/subjective_corev2.py, configs/datasets/subjective_cmp/subjective_creation.py, docs/en/advanced_guides/subjective_evaluation.md, docs/zh_cn/advanced_guides/subjective_evaluation.md, opencompass/openicl/icl_evaluator/lm_evaluator.py
=> [Feature] Add double order of subjective evaluation and removing duplicated response among two models

opencompass/lagent/actions/python_interpreter.py, opencompass/runners/slurm.py, opencompass/runners/slurm_sequential.py
=> [Feat] update python action and slurm

opencompass/datasets/gsm8k.py
Removed redundant code in GSM8KDataset.load method.
=> removed redundant code in GSM8KDataset.load method.

configs/eval_mixtral_8x7b.py
=> [Fix] fix a bug on configs/eval_mixtral_8x7b.py

configs/models/openai/gpt_3.5_turbo.py, configs/models/openai/gpt_3_5_turbo.py, configs/models/openai/gpt_4.py, docs/en/advanced_guides/subjective_evaluation.md, docs/zh_cn/advanced_guides/subjective_evaluation.md, opencompass/models/openai_api.py, tools/convert_alignmentbench.py
=> [Doc] Update Doc for Alignbench

opencompass/models/__init__.py, opencompass/models/openai_api.py
=> [Fix] minor fix openai

configs/eval_subjective_judge_pandalm.py, configs/models/judge_llm/auto_j/hf_autoj_bilingual_6b.py, configs/models/judge_llm/auto_j/hf_autoj_eng_13b.py, configs/models/judge_llm/auto_j/hf_autoj_eng_13b_4bit.py, configs/models/judge_llm/auto_j/hf_autoj_scen_classifier.py, configs/models/judge_llm/judgelm/hf_judgelm_13b_v1.py, configs/models/judge_llm/judgelm/hf_judgelm_33b_v1.py, configs/models/judge_llm/judgelm/hf_judgelm_7b_v1.py, configs/models/judge_llm/pandalm/hf_alpaca_pandalm_7b_v1.py, configs/models/judge_llm/pandalm/hf_pandalm_7b_v1.py, docs/en/advanced_guides/subjective_evaluation.md, docs/zh_cn/advanced_guides/subjective_evaluation.md, opencompass/partitioners/sub_naive.py, opencompass/partitioners/sub_size.py
=> Add Judgellms

configs/datasets/subjective_cmp/alignment_bench.py, configs/datasets/subjective_cmp/subjective_cmp.py, configs/datasets/subjective_cmp/subjective_corev2.py, configs/datasets/subjective_cmp/subjective_creation.py
=> [Fix] Quick fix for max_out_len in subjective evaluation

opencompass/summarizers/alignmentbench.py, opencompass/summarizers/corev2.py, opencompass/summarizers/creationv01.py, opencompass/tasks/subjective_eval.py, tools/convert_alignmentbench.py
=> [Feature] Add abbr for judgemodel in subjective evaluation

README.md, README_zh-CN.md
=> [News] add news for T-Eval

opencompass/partitioners/sub_naive.py, opencompass/summarizers/alignmentbench.py, opencompass/summarizers/corev2.py, opencompass/tasks/subjective_eval.py
=> [Fix] Fixed abbr erro of subjective alignbench and size partition

tools/convert_alignmentbench.py
=> [Fix] Update merge script for non-split settting

.gitignore, configs/datasets/humaneval/humaneval_gen_6d1cc2.py, configs/datasets/mbpp/mbpp_gen_caa7ab.py, configs/models/hf_internlm/hf_internlm_chat_7b_v11.py, configs/models/mistral/hf_mistral_7b_instruct_v02.py, configs/models/mixtral/hf_mixtral_8x7b_instruct_v01.py, configs/models/mixtral/hf_mixtral_8x7b_v01.py, configs/summarizers/groups/cibench.py, configs/summarizers/groups/mathbench.py, configs/summarizers/groups/plugineval.py, docs/en/advanced_guides/custom_dataset.md, docs/en/index.rst, docs/zh_cn/advanced_guides/custom_dataset.md, docs/zh_cn/index.rst, opencompass/datasets/__init__.py, opencompass/datasets/cibench.py, opencompass/datasets/custom.py, opencompass/datasets/gsm8k.py, opencompass/datasets/math.py, opencompass/openicl/icl_evaluator/icl_circular_evaluator.py, opencompass/summarizers/default.py, opencompass/tasks/openicl_eval.py, opencompass/utils/build.py, opencompass/utils/run.py, run.py
=> [Sync] Sync with internal codes

configs/datasets/collections/chat_medium.py, configs/datasets/collections/chat_small.py, configs/datasets/collections/leaderboard/qwen_chat.py, configs/datasets/mmlu/mmlu_gen.py, configs/datasets/mmlu/mmlu_gen_4d595a.py, configs/datasets/mmlu/mmlu_gen_a484b3.py, configs/eval_lightllm.py, opencompass/models/lightllm_api.py
=> Update LightllmApi and Fix mmlu bug

configs/datasets/humaneval/humaneval_passk_gen_8e312c.py, configs/datasets/humaneval/humaneval_repeat10_gen_8e312c.py, configs/datasets/mbpp/mbpp_passk_gen_1e1056.py, configs/datasets/mbpp/mbpp_repeat10_gen_1e1056.py, configs/datasets/mbpp/sanitized_mbpp_gen_1e1056.py, configs/datasets/mbpp/sanitized_mbpp_passk_gen_1e1056.py, configs/datasets/mbpp/sanitized_mbpp_repeat10_gen_1e1056.py, configs/eval_code_passk.py, configs/eval_code_passk_repeat_dataset.py, opencompass/datasets/mbpp.py
=> [Feat] support sanitized mbpp dataset

opencompass/tasks/subjective_eval.py
=> [Fix] SubSizePartition fix

configs/datasets/subjective_creationbench/creationbench_judgeby_gpt4.py, opencompass/datasets/__init__.py, opencompass/datasets/subject_alignmentbench.py, opencompass/datasets/subject_creationbench.py, opencompass/summarizers/__init__.py, opencompass/summarizers/alignmentbench.py, opencompass/summarizers/creationbench.py, opencompass/summarizers/subjective_post_process.py
=> [Feature] Add Creationbench Dataset

configs/datasets/mastermath2024v1/mastermath2024v1.py, configs/datasets/mastermath2024v1/mastermath2024v1_gen.py, configs/datasets/mastermath2024v1/mastermath2024v1_gen_be6318.py, opencompass/datasets/__init__.py, opencompass/datasets/mastermath2024v1.py
=> [Feature] Add new dataset mastermath2024v1

configs/api_examples/eval_api_qwen.py, opencompass/models/__init__.py, opencompass/models/qwen_api.py
Add support of Qwen API
Add support of Qwen API
No
see configs/api_examples/eval_api_qwen.py
**Before PR**:
**After PR**:
=> [Feature] Add support of Qwen API

opencompass/summarizers/alignmentbench.py, tools/convert_alignmentbench.py
=> [Fix] Fix small bug in alignbench

configs/datasets/subjective_multiround/functionalmt_zh_judgeby_gpt4.py, opencompass/datasets/__init__.py, opencompass/datasets/subject_multiround.py, opencompass/openicl/icl_inferencer/icl_chat_inferencer.py, opencompass/summarizers/__init__.py, opencompass/summarizers/alignmentbench.py, opencompass/summarizers/multiround.py
=> [Feature] Add multi_round dataset evaluation

configs/datasets/collections/leaderboard/qwen.py, configs/datasets/collections/leaderboard/qwen_chat.py, configs/datasets/drop/drop_gen.py, configs/datasets/drop/drop_gen_8a9ed9.py
fix the typos in fewshot prompt of DROP dataset
change all "Anawer" to "Answer"
**Before PR**:
**After PR**:
=> [Fix] fix typos in drop prompt

docs/en/get_started/installation.md, docs/zh_cn/get_started/installation.md
=> typo(installation.md): fix unzip commands

opencompass/models/openai_api.py
=> [Fix] add temperature in alles

requirements/agent.txt
=> [Fix] hot fix for requirements

configs/datasets/subjective_creationbench/creationbench_judgeby_gpt4_withref.py, configs/eval_subjective_creationbench.py, opencompass/datasets/subject_creationbench.py
=> [Feature] Add configs for creationbench

.github/workflows/pr-run-test.yml, .github/workflows/test.yml
=> Add test runner, one case, daily and pr trigger

configs/models/yi/hf_yi_6b_200k.py
delete meta_template in config file of yi_6b_200k model.
=> fix configs template for yi_6b_200k model

.github/workflows/pr-run-test.yml
=> Test runner update - split step, change schedule time and disable hf cache

configs/models/hf_internlm/hf_internlm2_chat_20b.py, configs/models/hf_internlm/hf_internlm2_chat_7b.py
=> Update hf_internlm2_chat template

configs/datasets/subjective/compassarena/compassarena_compare.py, configs/eval_subjective_compassarena.py, opencompass/datasets/subjective/__init__.py, opencompass/datasets/subjective/compass_arena.py, opencompass/datasets/subjective/subjective_cmp.py, opencompass/summarizers/subjective/__init__.py, opencompass/summarizers/subjective/compass_arena.py, opencompass/summarizers/subjective/utils.py
=> [Feature] add Compass arena

configs/datasets/IFEval/IFEval.md, configs/datasets/IFEval/IFEval_gen.py, configs/datasets/IFEval/IFEval_gen_3321a3.py, opencompass/datasets/IFEval/evaluation_main.py, opencompass/datasets/IFEval/ifeval.py, opencompass/datasets/IFEval/instructions.py, opencompass/datasets/IFEval/instructions_registry.py, opencompass/datasets/IFEval/instructions_util.py, opencompass/datasets/__init__.py
=> [Feature] Add IFEval

opencompass/models/baichuan_api.py, opencompass/models/baidu_api.py, opencompass/models/minimax_api.py, opencompass/models/moonshot_api.py, opencompass/models/qwen_api.py, requirements/api.txt
=> [Feature] Update API implementation

.github/workflows/pr-run-test.yml
=> add fail notify

configs/eval_chat_cibench_api.py, opencompass/datasets/cibench.py, opencompass/lagent/agents/react.py, opencompass/models/lagent.py, opencompass/openicl/icl_inferencer/icl_agent_inferencer.py, requirements/agent.txt
`opencompass.lagent.agents.ReAct` and `ReActPotocal` add extra parameters to control the role of prompt, which are used for API model.
**Before PR**:
**After PR**:
=> [Feat] minor update agent related

configs/datasets/MedBench/medbench_gen_0b4fff.py, opencompass/datasets/medbench/medbench.py
=> [Fix] Update MedBench

configs/api_examples/eval_api_zhipu_v2.py, opencompass/models/__init__.py, opencompass/models/zhipuai_v2_api.py, opencompass/runners/local_api.py
=> [Fix] Update Zhipu API and Fix issue min_out_len issue of API models

requirements/runtime.txt
the wheel file of rouge_chinese will overwrite the rouge package, causing bugs. Replacing it to the github code, which is the correct version.
change the setup requirements
**Before PR**:
**After PR**:
=> Update runtime.txt to fix rouge_chinese bugs.

configs/datasets/subjective/compassarena/compassarena_compare.py, configs/eval_subjective_compassarena.py, opencompass/summarizers/subjective/compass_arena.py, opencompass/summarizers/subjective/utils.py
=> [Fix] fix compass arena

configs/eval_internlm_chat_turbomind.py, docs/en/advanced_guides/evaluation_turbomind.md, docs/zh_cn/advanced_guides/evaluation_turbomind.md, opencompass/models/turbomind.py
add end_str for turbomind 
same as here
https://github.com/open-compass/opencompass/blob/5c6dc908cd50851bf7810eb90e47d8ef1434aa88/configs/models/hf_internlm/hf_internlm2_chat_7b.py#L34
**Before PR**:
**After PR**:
=> add end_str for turbomind

configs/eval_subjective_alignbench.py, configs/eval_subjective_alpacaeval.py, configs/eval_subjective_compassarena.py, configs/eval_subjective_corev2.py, configs/eval_subjective_creationbench.py, configs/eval_subjective_judge_pandalm.py, configs/eval_subjective_mtbench.py
=> [Fix] add do sample demo for subjective dataset

configs/eval_subjective_mtbench.py, opencompass/summarizers/subjective/mtbench.py
=> [Fix] hotfix for mtbench

configs/models/qwen/hf_qwen1_5_0_5b.py, configs/models/qwen/hf_qwen1_5_0_5b_chat.py, configs/models/qwen/hf_qwen1_5_14b.py, configs/models/qwen/hf_qwen1_5_14b_chat.py, configs/models/qwen/hf_qwen1_5_1_8b.py, configs/models/qwen/hf_qwen1_5_1_8b_chat.py, configs/models/qwen/hf_qwen1_5_4b.py, configs/models/qwen/hf_qwen1_5_4b_chat.py, configs/models/qwen/hf_qwen1_5_72b.py, configs/models/qwen/hf_qwen1_5_72b_chat.py, configs/models/qwen/hf_qwen1_5_7b.py, configs/models/qwen/hf_qwen1_5_7b_chat.py, configs/models/qwen/vllm_qwen1_5_72b.py, configs/models/qwen/vllm_qwen1_5_72b_chat.py
The official name of `qwen2-beta` is `qwen1.5`.
Derived from #885
=> [Fix] rename qwen2-beta -> qwen1.5

configs/models/chatglm/hf_chatglm2_6b.py
Following instructions in #410
=> [Fix] Fix chatglm2 config

configs/models/moss/hf_moss_moon_003_sft.py
This is a demo of `fnlp/moss-moon-003-sft`
https://huggingface.co/fnlp/moss-moon-003-sft#single-gpu
full sft dataset https://github.com/OpenLMLab/MOSS/blob/main/SFT_data/conversations/conversation_with_plugins/calculator/calculator_plugin_conversation_1.json
=> [Fix] Fix moss template config

configs/datasets/IFEval/IFEval.md, opencompass/datasets/IFEval/ifeval.py
=> [Fix] fix ifeval

configs/datasets/humaneval_plus/humaneval_plus_gen.py
=> [Fix] fix a bug of humanevalplus config

configs/models/deepseek/hf_ deepseek_coder_1_3b_instruct.py, configs/models/deepseek/hf_ deepseek_coder_33b_instruct.py, configs/models/deepseek/hf_ deepseek_coder_6_7b_instruct.py
=> [Feature] Add configs of deepseek-coder

README.md, README_zh-CN.md
=> [Docs] Update rank link in README

configs/datasets/subjective/multiround/mtbench_single_judge_diff_temp.py, configs/eval_subjective_mtbench.py, docs/en/advanced_guides/subjective_evaluation.md, docs/zh_cn/advanced_guides/subjective_evaluation.md, opencompass/openicl/icl_inferencer/icl_chat_inferencer.py, opencompass/summarizers/subjective/mtbench.py
=> [fix] add different temp for different question in mtbench

.github/workflows/link-check.yml, docs/en/advanced_guides/code_eval_service.md, docs/en/advanced_guides/evaluation_turbomind.md, docs/zh_cn/advanced_guides/code_eval_service.md, docs/zh_cn/advanced_guides/evaluation_turbomind.md
Derived from https://github.com/open-compass/opencompass/issues/858
=> [Fix] Update links and link checkers

configs/models/hf_internlm/hf_internlm2_chat_1_8b.py, configs/models/hf_internlm/hf_internlm2_chat_1_8b_sft.py, configs/models/hf_internlm/hf_internlm2_chat_20b.py, configs/models/hf_internlm/hf_internlm2_chat_20b_sft.py, configs/models/hf_internlm/hf_internlm2_chat_20b_with_system.py, configs/models/hf_internlm/hf_internlm2_chat_7b.py, configs/models/hf_internlm/hf_internlm2_chat_7b_sft.py, configs/models/hf_internlm/hf_internlm2_chat_7b_with_system.py
=> [Fix] fix a bug in internlm2 series configs

configs/datasets/QuALITY/QuALITY.md, configs/datasets/QuALITY/QuALITY_gen.py, configs/datasets/QuALITY/QuALITY_gen_c407cb.py, opencompass/datasets/QuALITY.py, opencompass/datasets/__init__.py
=> [Feature] Add the implement of QuALITY datasets

requirements/runtime.txt
modify the requirements file
modify the requirements/runtime.txt: numpy==1.23.4 --> numpy>=1.23.4
**Before PR**:
**After PR**:
=> modify the requirements/runtime.txt: numpy==1.23.4 --> numpy>=1.23.4

configs/datasets/subjective/compassarena/compassarena_compare.py, opencompass/partitioners/base.py, opencompass/tasks/subjective_eval.py
=> [Feature] add support for set prediction path

configs/datasets/apps/README.md, configs/datasets/taco/README.md, configs/datasets/taco/taco_gen.py, configs/datasets/taco/taco_gen_d82929.py, opencompass/datasets/taco.py
=> [Feat] Support TACO

configs/datasets/apps/README.md, configs/datasets/apps/apps_mini_gen.py, configs/datasets/apps/apps_mini_gen_c7893a.py, configs/datasets/taco/README.md, configs/datasets/taco/taco_gen.py, configs/datasets/taco/taco_gen_c7893a.py, opencompass/datasets/apps.py, opencompass/datasets/taco.py
=> [Fix] update apps/taco

opencompass/runners/base.py
Originaln simple lark bot run will come to a format fault.
Change status format into list.
**Before PR**:
**After PR**:
=> [Fix] base.py change status into list

configs/datasets/subjective/alpaca_eval/alpacav1_judgeby_gpt4.py, configs/datasets/subjective/alpaca_eval/alpacav2_judgeby_gpt4.py, configs/eval_subjective_alpacaeval.py, configs/eval_subjective_alpacaeval_oc.py, configs/subjective/eval_subjective_alpacaeval.py, docs/en/advanced_guides/subjective_evaluation.md, docs/en/get_started/installation.md, docs/zh_cn/advanced_guides/subjective_evaluation.md, docs/zh_cn/get_started/installation.md, opencompass/models/openai_api.py, opencompass/tasks/outer_eval/alpacaeval.py, opencompass/tasks/subjective_eval.py, requirements/extra.txt
=> [Feature] support alpacaeval_v2

docs/zh_cn/advanced_guides/new_model.md
This PR aims to correct a typographical error in the "Supporting New Models" document within the Chinese documentation, enhancing the document's accuracy and readability.
Summary of Changes: In the "Supporting New Models" section of the Chinese documentation, under the secondary title "新增第三方模型," I corrected the original sentence from "新增基于API的模型" to "新增基于第三方的模型."
Compatibility: This modification is limited to correcting content in the documentation and does not involve any code changes, thus it will not affect backward compatibility.
Since this PR primarily addresses corrections in the documentation and does not introduce new features, this section is not applicable.
**Before PR**:
- [√] Pre-commit or other linting tools are used to fix the potential lint issues.
- [√] Bug fixes are fully …
=> updates docs

configs/datasets/ChemBench/ChemBench_gen.py, configs/eval_chembench.py, opencompass/datasets/__init__.py, opencompass/datasets/chembench.py
We build ChemBench for testing the capabilities of  LLMs on chemistry tasks. We want to add 
it to opencompass.
1. modify file: opencompass/opencompass/datasets/__init__.py
add: from .chembench import *
2. add file: opencompass/opencompass/datasets/chembench.py
3. add file: opencompass/configs/datasets/ChemBench
4. add file: opencompass/data/ChemBench
Does the modification …
=> add ChemBench

configs/datasets/subjective/multiround/functionalmt_zh_judgeby_gpt4.py, configs/eval_subjective_functional_multiround.py, opencompass/openicl/icl_evaluator/lm_evaluator.py, opencompass/openicl/icl_inferencer/icl_chat_inferencer.py, opencompass/summarizers/subjective/multiround.py
=> [Fix] fix multiround

README.md, README_zh-CN.md, configs/datasets/subjective/arena_hard/README.md, configs/datasets/subjective/arena_hard/arena_hard_scoring.py, configs/eval_subjective_arena_hard.py, docs/en/advanced_guides/subjective_evaluation.md, docs/zh_cn/advanced_guides/subjective_evaluation.md, opencompass/datasets/subjective/__init__.py, opencompass/datasets/subjective/arena_hard.py, opencompass/runners/slurm_sequential.py, opencompass/summarizers/subjective/__init__.py, opencompass/summarizers/subjective/arenahard.py
=> [Feature] support arenahard evaluation

opencompass/tasks/openicl_eval.py, opencompass/tasks/openicl_infer.py
=> fix: python path bug

opencompass/utils/file.py, opencompass/utils/run.py
=> fix output typing, change mutable list to immutable tuple

configs/eval_internlm_flames_chat.py
=> [Fix] fix prompt template

opencompass/datasets/cmb.py
=> [Fix] fix cmb dataset

opencompass/datasets/__init__.py
=> [Fix] fix links

opencompass/cli/main.py, opencompass/utils/run.py
(cherry picked from commit 4beb6d9ab655d8a626971841b7acfd9fae9d438f)
If this PR introduces a new feature, it is better to …
=> [Sync] Update accelerator

configs/eval_subjective_alpacaeval_official.py, opencompass/summarizers/subjective/alpacaeval.py, opencompass/tasks/outer_eval/alpacaeval.py
=> [Fix] fix alpacaeval while add caching path

opencompass/datasets/lawbench/evaluation_functions/wsjd.py
=> [Fix] temporary files using tempfile

opencompass/models/openai_api.py
=> [Fix] add support for lmdeploy api judge

docs/en/get_started/faq.md, docs/en/get_started/quick_start.md, docs/en/user_guides/experimentation.md, docs/zh_cn/get_started/faq.md, docs/zh_cn/get_started/quick_start.md, docs/zh_cn/user_guides/experimentation.md, opencompass/cli/main.py, opencompass/utils/run.py
=> [Docs] Remove --no-batch-padding and Use --hf-num-gpus

configs/models/opt/hf_opt_125m.py, configs/models/opt/hf_opt_350m.py
=> [Fix] Rollback opt model configs

configs/eval_subjective_alpacaeval_official.py, requirements/extra.txt
=> [Fix] fix pip version

.github/scripts/oc_score_baseline.yaml, .github/workflows/daily-run-test.yml
add flash_attn installation in  daily testcase.
=> flash attn installation in daily testcase

configs/datasets/MathBench/mathbench_2024_gen_fc2a24.py, configs/datasets/MathBench/mathbench_gen.py, configs/eval_mathbench.py, configs/summarizers/groups/mathbench_v1_2024.py, configs/summarizers/groups/mathbench_v1_2024_lang.py
Update mathbench summarizer & fix cot setting 
Update mathbench summarizer & fix cot setting 
**Before PR**:
**After PR**:
=> Update MathBench summarizer & fix cot setting 

.owners.yml
=> [Feat] Update owners for issues

configs/datasets/rolebench/instruction_generalization_zh.py
RougeEvaluator get wrong score on chinese corpus.
=> [Fix] Fix rouge evaluator of rolebench_zh

configs/datasets/compassbench_v1_3/compassbench_v1_3_objective_gen_068af0.py, configs/datasets/subjective/compassbench/compassbench_checklist.py
=> [Fix] Update path and folder

configs/eval_compassbench_v1_3_subjective.py, opencompass/summarizers/subjective/compassbench_v13.py
=> CompassBench subjective summarizer added

configs/datasets/MathBench/mathbench_2024_gen_19e486.py, configs/datasets/MathBench/mathbench_gen.py
Redirect the default MathBench config to the same as the MathBench paper
=> Fix MathBench Generation Config

opencompass/models/openai_api.py
I deploy a model with OpenAI-compatible server. But I get an error when running benchmarks in opencompass since it always load tokenizer with tiktoken.
`hf_tokenizer` will be used when `tiktoken.encoding_for_model()` failed
**Before PR**:
**After PR**:
=> [Fix] Support HF models deployed with an OpenAI-compatible API.

docs/en/advanced_guides/needleinahaystack_eval.md, docs/zh_cn/advanced_guides/needleinahaystack_eval.md, opencompass/datasets/needlebench/multi.py, opencompass/datasets/needlebench/origin.py, opencompass/datasets/needlebench/parallel.py
This PR addresses issue #1338 by adding NeedleBench dataset to Hugging Face.
=> [Feature] Make NeedleBench available on HF

opencompass/runners/local.py
Fixed an issue with environmental indicators determined when using NPU.
Remove extra ampersands.
No
=> 【bug fix】: Remove extra ampersands.

configs/models/pulse/hf_pulse_7b.py
Pulse-7b模型配置
https://github.com/openmedlab/PULSE
https://huggingface.co/OpenMEDLab/PULSE-7bv5
=> add support for hf_pulse_7b

opencompass/datasets/LCBench.py, opencompass/datasets/humaneval.py
=> [Fix] Update get_data_path for LCBench and HumanEval

opencompass/models/turbomind.py
=> [Bug] Fix bug in turbomind

.pre-commit-config-zh-cn.yaml, .pre-commit-config.yaml, README.md, README_zh-CN.md, configs/models/gemma/hf_gemma2_27b.py, configs/models/gemma/hf_gemma2_27b_it.py, configs/models/gemma/hf_gemma2_2b.py, configs/models/gemma/hf_gemma2_2b_it.py, configs/models/gemma/hf_gemma2_9b.py, configs/models/gemma/hf_gemma2_9b_it.py, opencompass/configs/datasets/calm/README.md, opencompass/configs/datasets/calm/calm.py, opencompass/configs/models/gemma/hf_gemma2_27b.py, opencompass/configs/models/gemma/hf_gemma2_27b_it.py, opencompass/configs/models/gemma/hf_gemma2_2b.py, opencompass/configs/models/gemma/hf_gemma2_2b_it.py, opencompass/configs/models/gemma/hf_gemma2_9b.py, opencompass/configs/models/gemma/hf_gemma2_9b_it.py, opencompass/configs/summarizers/groups/calm.py, opencompass/datasets/huggingface.py, opencompass/models/openai_api.py, tools/compare_configs.py
=> [Feature] Support OpenAI ChatCompletion

opencompass/datasets/ceval.py, opencompass/datasets/cmmlu.py, opencompass/datasets/gsm8k.py, opencompass/datasets/strategyqa.py, opencompass/datasets/winogrande.py, tests/dataset/test_ms_datasets.py
Fix modelscope dataset load problem
remove `trust_remote_code=True` when loading dataset
**Before PR**:
**After PR**:
=> Fix modelscope dataset load problem

opencompass/datasets/lawbench/evaluation_functions/ljp_imprison.py
…luation(#1402)
If this PR introduces a new feature, it is better to list some use cases here and update the …
=> [Fix] the issue where scores are negative in the Lawbench dataset evaluation(#1402)

opencompass/datasets/longbench/longbench_vcsum.py
=> longbench dataset load fix

configs/datasets/subjective/fofo/fofo_bilingual_judge.py, configs/datasets/subjective/wildbench/wildbench_pair_judge.py, opencompass/configs/datasets/subjective/fofo/fofo_bilingual_judge.py, opencompass/configs/datasets/subjective/fofo/fofo_judge.py, opencompass/configs/datasets/subjective/wildbench/wildbench_pair_judge.py, opencompass/datasets/subjective/fofo.py, opencompass/datasets/subjective/mtbench101.py, opencompass/datasets/subjective/wildbench.py, opencompass/utils/datasets_info.py
=> [Update] Support auto-download of FOFO/MT-Bench-101

opencompass/utils/run.py
=> [Feature] Add model support for 'huggingface_above_v4_33' when using '-a'

configs/datasets/truthfulqa/truthfulqa_gen_5ddc62.py, configs/models/gemma/hf_gemma2_27b_it.py, configs/models/gemma/hf_gemma2_2b_it.py, configs/models/gemma/hf_gemma2_9b_it.py, configs/models/gemma/hf_gemma_2b_it.py, configs/models/gemma/hf_gemma_7b_it.py, opencompass/configs/datasets/truthfulqa/truthfulqa_gen_5ddc62.py, opencompass/configs/models/gemma/hf_gemma2_27b_it.py, opencompass/configs/models/gemma/hf_gemma2_2b_it.py, opencompass/configs/models/gemma/hf_gemma2_9b_it.py, opencompass/configs/models/gemma/hf_gemma_2b_it.py, opencompass/configs/models/gemma/hf_gemma_7b_it.py, opencompass/datasets/scicode.py, opencompass/utils/datasets_info.py
=> [Fix] Update SciCode and Gemma model

opencompass/utils/run.py
=> [Fix] Fix cli evaluation for multiple models

configs/eval_academic_leaderboard_202407.py, opencompass/utils/datasets_info.py
=> [Feature] Update Lint and Leaderboard

opencompass/models/openai_api.py
Make it easy to use by setting OPENAI_BASE_URL env + CLI
Use openai-sdk official base_url env
https://github.com/openai/openai-python/blob/05fa732c024b55ddda1f5f8b107ce78233acd3ce/src/openai/_client.py#L118
If so, please describe how it breaks the compatibility and how …
=> Make OPENAI_API_BASE compatible with openai default env

opencompass/models/openai_api.py
- Add support for the `extra_body` parameter in OpenAISDK, useful for OpenAI-compatible API models where passing extra parameters is needed.
- Add support for connecting via proxy url when using OpenAI models.
- Added the `extra_body` parameter to `self.openai_client.chat.completions.create` in `OpenAISDK`.
- Added `openai_proxy_url` parameter to `OpenAI` and `OpenAISDK` classes, which adds support for specifying a proxy URL.
- Fixed typo for `self.openai_client` in `OpenAISDK`.
Does the modification introduce changes that break …
=> [Feature] Added `extra_body` support for OpenAISDK; Added support for proxy URL when connecting to OpenAI's API.

.github/scripts/eval_regression_chat.py, .github/workflows/daily-run-test.yml, .github/workflows/pr-run-test.yml
after machine reboot, need to change conda activate method.
=> [ci] fix test env

.github/scripts/oc_score_assert.py, .github/workflows/daily-run-test.yml, opencompass/models/lmdeploy_pytorch.py
1. remove phi-3-small-8k-instruct-hf from case list because of the model's own bug on transformers
2. add pip list after test env is ready for issue reproduce
3. fix potiential bug, the element numbers of version_info is unstable
=> [ci] fix badcase and add env info

opencompass/models/lmdeploy_pytorch.py, opencompass/models/turbomind_with_tf_above_v4_33.py
https://github.com/InternLM/lmdeploy/blob/edcdd8e36520b8bf7dbc99feecd2d2822c4cb5ba/lmdeploy/messages.py#L74  
lmdeploy interface add stop_token_ids
=> [Fix] compatible lmdeploy interface type changes

configs/models/hf_llama/hf_llama3_1_70b_instruct.py, configs/models/hf_llama/hf_llama3_1_8b_instruct.py, configs/models/hf_llama/lmdeploy_llama3_1_70b_instruct.py, configs/models/mistral/vllm_mixtral_large_instruct_2407.py, configs/models/openbmb/hf_minicpm3_4b.py, configs/models/phi/hf_phi_3_5_MoE_instruct.py, configs/models/phi/hf_phi_3_5_mini_instruct.py, configs/summarizers/groups/humanevalx.py, opencompass/configs/models/hf_llama/hf_llama3_1_70b_instruct.py, opencompass/configs/models/hf_llama/hf_llama3_1_8b_instruct.py, opencompass/configs/models/hf_llama/lmdeploy_llama3_1_70b_instruct.py, opencompass/configs/models/hf_llama/lmdeploy_llama3_1_8b_instruct.py, opencompass/configs/models/mistral/vllm_mixtral_large_instruct_2407.py, opencompass/configs/models/openbmb/hf_minicpm3_4b.py, opencompass/configs/models/phi/hf_phi_3_5_MoE_instruct.py, opencompass/configs/models/phi/hf_phi_3_5_mini_instruct.py, opencompass/configs/summarizers/groups/humanevalx.py, opencompass/datasets/ds1000.py, opencompass/datasets/humanevalx.py, opencompass/utils/datasets_info.py
=> [Feature] Update Models

configs/datasets/ARC_c/ARC_c_few_shot_ppl.py, configs/datasets/SuperGLUE_BoolQ/SuperGLUE_BoolQ_few_shot_ppl.py, configs/datasets/race/race_few_shot_ppl.py, opencompass/configs/datasets/ARC_c/ARC_c_few_shot_ppl.py, opencompass/configs/datasets/SuperGLUE_BoolQ/SuperGLUE_BoolQ_few_shot_ppl.py, opencompass/configs/datasets/race/race_few_shot_ppl.py
Few-shot PPL update for datasets ARC, Race, BoolQ
=> Few-shot PPL update for datasets

README.md, README_zh-CN.md, configs/models/openai/o1_mini_2024_09_12.py, configs/models/openai/o1_preview_2024_09_12.py, opencompass/configs/models/openai/o1_mini_2024_09_12.py, opencompass/configs/models/openai/o1_preview_2024_09_12.py, opencompass/models/openai_api.py
=> [Feature] Support OpenAI O1 models

opencompass/models/base_api.py
This is a fix for the [issue](https://github.com/open-compass/opencompass/issues/1362). This issue describes a problem where specifying a `system_prompt` in the `meta_template` does not work as expected because `APITemplateParser` does not handle the content within the **begin section** of the meta_template. This seems to fall short of user expectations. When users write the meta_template in the following manner, they likely expect the system_prompt to be added to the prompt list.
```
_meta_template=dict(
begin=dict(role='SYSTEM', prompt='You are a cat'),
round=[
dict(role='HUMAN', api_role='HUMAN'),
dict(role='BOT', api_role='BOT', generate=True)
],
)
```
Expected behavior:
```
"origin_prompt": [
{
"prompt": "You are a cat.",
"role": "SYSTEM"
},
{
"role": "HUMAN",
"prompt": "Question: …
```
=> [FIX] Added handling for the "begin section" in meta_template to APITemplateParser

opencompass/models/base_api.py, opencompass/models/openai_api.py, opencompass/openicl/icl_inferencer/icl_gen_inferencer.py
=> [Feature] Support verbose for OpenAI API

configs/summarizers/groups/cibench.py, opencompass/configs/summarizers/groups/cibench.py
=> BUG: Update cibench.py

opencompass/models/__init__.py, opencompass/models/interntrain.py
=> [Feature] Add InternTrain

README.md
Correct typos in the README file.
=> [Fix] Correct typos

configs/eval_corebench_2409_longcontext.py, configs/eval_corebench_2409_objective.py, configs/eval_corebench_2409_subjective.py
=> [Feature] Add Config for CoreBench

opencompass/runners/dlc.py
=> [Feature] Add dlc sleep time

configs/datasets/subjective/followbench/followbench_llmeval.py, opencompass/configs/datasets/subjective/followbench/followbench_llmeval.py
=> [BUG] fix followbench dataset config

opencompass/models/bailing_api_oc.py
=> bugfix: fix the token setting.

opencompass/datasets/GaokaoBench.py
=> [BUG]GaokaoBench dataset fix

opencompass/models/interntrain.py
=> [Fix] fix eos and add comments for InternTrain

opencompass/__init__.py
=> [BUMP] Bump version to 0.3.3

.github/scripts/oc_score_assert.py, .github/scripts/oc_score_baseline.yaml, .github/workflows/daily-run-test.yml
1. Temporarily delete glm4 testcase because of transformers update
2. update gemma2 score
3. remove max-num-workers params in command testcase
=> [ci] fix testcase failure

opencompass/models/interntrain.py
=> [Fix] InternTrain get_loglikelihood

.github/workflows/lint.yml
=> [Bug] fix pre-commit hook

opencompass/runners/dlc.py
=> [Fix] Update dlc runner python env

opencompass/models/interntrain.py
=> [Fix] Fix interntrain's tokenizer truncate

.github/workflows/daily-run-test.yml
reset timeout param to fix dailytest's failure
=> [ci] Reset timeout param

opencompass/models/turbomind_with_tf_above_v4_33.py
=> remove prefix bos_token from messages when using lmdeploy as the accelerator

.github/scripts/oc_score_baseline.yaml, requirements/runtime.txt
1. fix huggingface-hub version because of https://github.com/UKPLab/sentence-transformers/issues/3001
2. fix evalation baseline because of https://github.com/open-compass/opencompass/pull/1623
=> [ci] test pr staging fixed

configs/eval_judgerbench.py
=> [Update] eval_judgerbench.py

configs/models/qwen2_5/hf_qwen2_5_14b_instruct.py, configs/models/qwen2_5/hf_qwen2_5_32b_instruct.py, configs/models/qwen2_5/hf_qwen2_5_72b_instruct.py, configs/models/qwen2_5/hf_qwen2_5_7b_instruct.py, opencompass/configs/models/qwen2_5/hf_qwen2_5_14b_instruct.py, opencompass/configs/models/qwen2_5/hf_qwen2_5_32b_instruct.py, opencompass/configs/models/qwen2_5/hf_qwen2_5_72b_instruct.py, opencompass/configs/models/qwen2_5/hf_qwen2_5_7b_instruct.py
=> [Fix] Qwen 2.5 model config

configs/datasets/livecodebench/README.md, configs/datasets/livecodebench/livecodebench_gen.py, configs/datasets/livecodebench/livecodebench_gen_b2b0fd.py, configs/models/hf_llama/hf_llama3_1_8b_instruct.py, opencompass/configs/datasets/livecodebench/README.md, opencompass/configs/datasets/livecodebench/livecodebench_gen.py, opencompass/configs/datasets/livecodebench/livecodebench_gen_b2b0fd.py, opencompass/configs/models/hf_llama/hf_llama3_1_8b_instruct.py, opencompass/datasets/__init__.py, opencompass/datasets/livecodebench/__init__.py, opencompass/datasets/livecodebench/evaluator.py, opencompass/datasets/livecodebench/execute_utils.py, opencompass/datasets/livecodebench/extract_utils.py, opencompass/datasets/livecodebench/livecodebench.py, opencompass/datasets/livecodebench/pass_k_utils.py, opencompass/datasets/livecodebench/prompts.py, opencompass/datasets/livecodebench/testing_util.py, opencompass/openicl/icl_evaluator/icl_base_evaluator.py, opencompass/utils/datasets_info.py, requirements/runtime.txt
=> [Feature] Support LiveCodeBench

opencompass/summarizers/subjective/common_summarizer.py
=> [Fix] Update common summarizer regex extraction

opencompass/datasets/humaneval.py
=> [Update] Add internal humaneval postprocess

opencompass/models/turbomind_with_tf_above_v4_33.py
In some models, after decoding `eos_token_id`, the word starts with a blank. When it is encode back, the token_id is not the `eos_token_id`.
If this PR introduces a new feature, it is better to list some use cases …
=> strip stop_words to avoid blanks

opencompass/runners/dlc.py
Update DLC runner to fit different versions of dlc
=> [Update] Update DLC runner

opencompass/runners/dlc.py, opencompass/runners/local.py, opencompass/runners/slurm_sequential.py, opencompass/runners/volc.py
avoid name conflict;add keep_tmp_file flag to support keep the temp config file.
If this PR introduces a new feature, it …
=> [Update] Fix issue of *_param.py

opencompass/configs/datasets/humaneval/internal_humaneval_gen_ce6b06.py, opencompass/configs/datasets/humaneval/internal_humaneval_gen_d2537e.py, opencompass/datasets/humaneval.py
=> Internal humaneval add

configs/datasets/subjective/wildbench/wildbench_pair_judge.py, opencompass/configs/datasets/subjective/wildbench/wildbench_pair_judge.py
=> [Update] Update wildbench max_seq_len

opencompass/utils/datasets_info.py
=> [Update] Update Needlebench OSS path

opencompass/configs/models/chatglm/hf_glm4_9b.py, opencompass/configs/models/gemma/lmdeploy_gemma_27b_it.py, opencompass/configs/models/gemma/lmdeploy_gemma_9b_it.py, opencompass/configs/models/qwen2_5/hf_qwen_2_5_14b.py, opencompass/configs/models/qwen2_5/hf_qwen_2_5_32b.py, opencompass/configs/models/qwen2_5/hf_qwen_2_5_7b.py
[Update] Add new model configs
=> [Update] Add new model configs

opencompass/configs/models/deepseek/lmdeploy_deepseek_v2.py, opencompass/configs/models/deepseek/lmdeploy_deepseek_v2_5.py
=> [Update] Add lmdeploy DeepSeek configs

README.md, README_zh-CN.md, configs/datasets/GaokaoBench/GaokaoBench_gen_5cfe9e.py, configs/datasets/GaokaoBench/GaokaoBench_mixed_9af5ee.py, configs/datasets/GaokaoBench/GaokaoBench_no_subjective_gen_4c31db.py, configs/datasets/GaokaoBench/GaokaoBench_no_subjective_gen_d21e37.py, configs/datasets/nq/nq_open_1shot_gen_01cf41.py, configs/datasets/nq/nq_open_1shot_gen_20a989.py, configs/datasets/nq/nq_open_1shot_gen_2e45e5.py, configs/datasets/nq/nq_open_gen_e93f8a.py, configs/datasets/wikibench/wikibench_few_shot_ppl_c23d79.py, configs/datasets/wikibench/wikibench_gen_0978ad.py, configs/datasets/wikibench/wikibench_gen_f96ece.py, opencompass/__init__.py, opencompass/configs/datasets/GaokaoBench/GaokaoBench_gen_5cfe9e.py, opencompass/configs/datasets/GaokaoBench/GaokaoBench_mixed_9af5ee.py, opencompass/configs/datasets/GaokaoBench/GaokaoBench_no_subjective_gen_4c31db.py, opencompass/configs/datasets/GaokaoBench/GaokaoBench_no_subjective_gen_d21e37.py, opencompass/configs/datasets/nq/nq_open_1shot_gen_01cf41.py, opencompass/configs/datasets/nq/nq_open_1shot_gen_20a989.py, opencompass/configs/datasets/nq/nq_open_1shot_gen_2e45e5.py, opencompass/configs/datasets/nq/nq_open_gen_e93f8a.py, opencompass/configs/datasets/wikibench/wikibench_few_shot_ppl_c23d79.py, opencompass/configs/datasets/wikibench/wikibench_gen_0978ad.py, opencompass/configs/datasets/wikibench/wikibench_gen_f96ece.py, opencompass/datasets/GaokaoBench.py, opencompass/datasets/natural_question.py, opencompass/datasets/wikibench.py, opencompass/utils/datasets_info.py
=> [Fix] the automatically download for several datasets

opencompass/configs/datasets/mmmlu_lite/README.md, opencompass/configs/datasets/mmmlu_lite/mmmlu_lite_gen_c51a84.py, opencompass/datasets/mmmlu.py, opencompass/utils/datasets_info.py
=> Update mmmlu_lite dataload

opencompass/models/turbomind.py
=> Fix  get_loglikehood error with lmdeploy as the accelerator

.github/workflows/pr-run-test.yml
=> [ci] fix pr test bug

opencompass/utils/datasets_info.py
1. Add Auto-download for followbench
=> [Update] Auto-download for followbench

README.md, configs/eval_musr.py, opencompass/configs/datasets/musr/README.md, opencompass/configs/datasets/musr/musr_gen.py, opencompass/configs/summarizers/groups/musr_average.py, opencompass/datasets/__init__.py, opencompass/datasets/musr/__init__.py, opencompass/datasets/musr/murder_mystery_solved_ex.py, opencompass/datasets/musr/musr.py, opencompass/datasets/musr/object_placements_solved_ex.py, opencompass/datasets/musr/team_allocation_solved_ex.py, opencompass/datasets/musr/tree.py, opencompass/utils/datasets_info.py
MuSR (Multistep Soft Reasoning) is a dataset designed to evaluate language models (LLMs) on complex reasoning tasks embedded in natural language narratives. Created to challenge state-of-the-art models like GPT-4 and others, MuSR emphasizes nuanced reasoning across different domains, including social and physical reasoning, commonsense reasoning, and planning, with tasks framed within realistic scenarios such as murder mysteries, object placements, and team allocations.
Current large language models can perform complex tasks through prompting techniques like chain-of-thought reasoning. However, robust multistep reasoning remains challenging. MuSR addresses these limitations by evaluating LLM performance on tasks involving multistep reasoning in three domains:
- **Murder Mysteries**: …
=> MuSR Datset Evaluation

.github/scripts/oc_score_baseline_fullbench.yaml, .github/scripts/oc_score_baseline_testrange.yaml, .github/workflows/daily-run-test.yml
=> [ci] update testcase baseline

opencompass/datasets/math.py, opencompass/utils/datasets_info.py
1. Add `test_prm800k_500.json` subset into auto-download OSS
2. Update Math Dataset config to support different file_name
=> [Feature] Update Math data

opencompass/__init__.py
=> [BUMP] Bump version to 0.3.6

opencompass/models/bailing_api_oc.py
Bailing Model Reasoning has supported the more abundant error code to show the detail. The PR can take the actions based on these error code. 
Retry according to the reasons indicated by the error code 
If so, please describe how it breaks the compatibility and how the …
=> support new error code

configs/eval_math_llm_judge_internal.py, opencompass/configs/datasets/math/math_0shot_llm_judge_v2_gen_31d777.py, opencompass/datasets/compassbench_obj.py, opencompass/datasets/gaokao_math.py, opencompass/utils/model_postprocessors.py
=> Update MATH dataset with model judge

opencompass/configs/datasets/ARC_Prize_Public_Evaluation/README.md, opencompass/configs/datasets/ARC_Prize_Public_Evaluation/arc_prize_public_evaluation_gen.py, opencompass/configs/datasets/ARC_Prize_Public_Evaluation/arc_prize_public_evaluation_gen_872059.py, opencompass/datasets/arc_prize_public_evaluation.py, opencompass/utils/datasets_info.py
Support Arc Prize Public Evaluation Set.
Add Arc Prize Public Evaluation configurations and README.
**Before PR**:
**After PR**:
=> [Update] Support Arc Prize Public Evaluation

configs/eval_simpleqa.py, opencompass/configs/datasets/SimpleQA/README.md, opencompass/configs/datasets/SimpleQA/simpleqa_gen.py, opencompass/configs/datasets/SimpleQA/simpleqa_gen_0283c3.py, opencompass/configs/summarizers/simpleqa.py, opencompass/datasets/__init__.py, opencompass/datasets/simpleqa.py, opencompass/utils/datasets_info.py
=> [Feature] Add Openai Simpleqa dataset

opencompass/configs/datasets/livemathbench/README.md, opencompass/configs/datasets/livemathbench/livemathbench_gen.py, opencompass/configs/datasets/livemathbench/livemathbench_gen_caed8f.py, opencompass/datasets/livemathbench/__init__.py, opencompass/datasets/livemathbench/livemathbench.py, opencompass/datasets/livemathbench/prompts.py
Support LiveMathBench.
Add LiveMathBench configurations including loader, evaluator, and README.
**Before PR**:
**After PR**:
=> [Feature] Support LiveMathBench

opencompass/__init__.py, opencompass/configs/models/deepseek/lmdeploy_deepseek_v2_lite.py, opencompass/configs/models/gemma/lmdeploy_gemma_27b.py, opencompass/configs/models/gemma/lmdeploy_gemma_9b.py
=> [Bump] Bump version to 0.3.7

configs/datasets/subjective/compassarena/compassarena_compare_new.py, configs/datasets/subjective/wildbench/wildbench_pair_judge_new.py, configs/eval_academic_leaderboard_202412.py, opencompass/configs/datasets/bbh/bbh_0shot_nocot_gen_925fc4.py, opencompass/configs/datasets/korbench/korbench_mixed_gen_d00bdd.py, opencompass/configs/datasets/korbench/korbench_single_0_shot_gen.py, opencompass/configs/datasets/korbench/korbench_single_3_shot_gen.py, opencompass/configs/datasets/math/math_prm800k_500_0shot_cot_gen.py, opencompass/configs/datasets/subjective/compassarena/compassarena_compare_new.py, opencompass/configs/datasets/subjective/wildbench/wildbench_pair_judge_new.py
1. Add OC academic 2412 evaluation
2. Fix Korbench `prompt_mode` issue
3. Update subjective new evaluation configuration max_out_len to keep sync with existing configurations
=> [Feature] Add OC academic 2412

opencompass/summarizers/subjective/common_summarizer.py
add return in summarize
the result score  can be automatically displayed statistically in the subjective all results.
test result is in csv is:
Dataset,Detailed Scores,xxx,yyyy
qa_bench_identity,total,0.95,0.91
qa_bench_safecheck,total,0.46,0.94
qa_bench_safecheck,ch,0.68,0.99
qa_bench_safecheck,en,0.12,0.86
qa_bench_sensitivity,total,0.99,0.84
=> [ci] add common_summarizer return

opencompass/datasets/subjective/compassbench_checklist.py, opencompass/summarizers/subjective/__init__.py, opencompass/summarizers/subjective/qacompassbench.py, opencompass/utils/datasets_info.py
1. add a new qa summerizer
2. use get_data_path in CompassBenchCheklistDataset
3. add new dataset config in opencompass/utils/datasets_info.py
=> add new dataset summerizer

README.md, README_zh-CN.md, opencompass/__init__.py
=> [Bump] Bump version to 0.3.8

opencompass/runners/dlc.py
=> [Fix] Fix lark report is None

README.md, README_zh-CN.md, configs/eval_academic_leaderboard_202412.py, opencompass/configs/datasets/livecodebench/livecodebench_gen_a4f90b.py, opencompass/configs/datasets/math/math_prm800k_500_0shot_cot_gen.py, opencompass/datasets/bigcodebench/bigcodebench.py
1. Update OC academic 202412 (release the max_out_len for some datasets, remove CMO dataset)
2. Update pass@1 metrics for Bigcodebench from 0~100
=> [Update] Update OC academic 202412

.github/workflows/daily-run-test.yml, .github/workflows/pr-run-test.yml
=> [ci] remove daily step retry and update pr score

.github/workflows/pr-run-test.yml, .github/workflows/publish-to-pypi.yml
Update deploy python version from python 3.7 - 3.10
=> [CI] Update deploy python version

.github/workflows/publish-to-pypi.yml
=> [CI] Pypi deploy workflow update

opencompass/configs/datasets/TheoremQA/ThroremQA_0shot_cot_gen_8acdf7.py, opencompass/datasets/TheoremQA/__init__.py, opencompass/datasets/TheoremQA/main.py
| dataset | version | metric | mode | internlm2_5-7b-chat-turbomind | qwen2.5-7b-instruct-turbomind | deepseek-v2_5-1210-turbomind | deepseek-v2_5-turbomind |
|----- | ----- | ----- | ----- | ----- | ----- | ----- | -----|
| TheoremQA | 8acdf7 | score | gen | 18.38 | 42.62 | 51.38 | 53.75 |
=> [Update] Add Theorem QA 0shot CoT config

opencompass/evaluator/generic_llm_evaluator.py, opencompass/tasks/subjective_eval.py
=> [Fix] Fix output_path

opencompass/__init__.py
=> [BUMP] Bump version to 0.3.9

opencompass/configs/datasets/aime2024/aime2024_0shot_nocot_genericllmeval_xml_gen_2b9dc2.py, opencompass/configs/datasets/cmmlu/cmmlu_stem_0shot_nocot_xml_gen_3653db.py, opencompass/configs/datasets/gpqa/gpqa_0shot_nocot_genericllmeval_xml_gen_772ea0.py, opencompass/configs/datasets/korbench/korbench_single_0shot_genericllmeval_xml_gen_17854d.py, opencompass/configs/datasets/livereasonbench/livereasonbench_genericllmeval_xml_gen_f990de.py, opencompass/configs/datasets/livestembench/livestembench_0shot_noncot_gen_2e6d10.py, opencompass/configs/datasets/livestembench/livestembench_0shot_noncot_xml_gen_2e6d10.py, opencompass/configs/datasets/livestembench/livestembench_gen_3e3c50.py, opencompass/configs/datasets/math/math_prm800k_500_0shot_nocot_genericllmeval_xml_gen_63a000.py, opencompass/configs/datasets/mmlu/mmlu_stem_0shot_xml_gen_216503.py, opencompass/datasets/livemathbench/livemathbench.py, opencompass/evaluator/generic_llm_evaluator.py, opencompass/utils/datasets.py, opencompass/utils/datasets_info.py, opencompass/utils/text_postprocessors.py
=> [Update] Update o1 eval prompt 

opencompass/configs/datasets/livemathbench/livemathbench_greedy_gen_efb20d.py, opencompass/datasets/livemathbench/livemathbench.py
=> [Update] Update LiveMathBench

.github/workflows/lint.yml, README.md, README_zh-CN.md, opencompass/configs/models/hf_internlm/hf_internlm3_8b_instruct.py, opencompass/configs/models/hf_internlm/lmdeploy_internlm3_8b_instruct.py
=> [Feature] Add support for InternLM3

.github/workflows/daily-run-test.yml
set python version in daily test
=> [ci] set python version in daily test

.github/scripts/oc_score_baseline_fullbench.yaml, .github/scripts/oc_score_baseline_testrange.yaml, .github/workflows/daily-run-test.yml, opencompass/runners/dlc.py
1. change score becuase of v4.0.0 and transformers's upgrade
2. only notify of scheduled tasks
=> [ci] update daily test scores

examples/eval_simpleqa.py, opencompass/cli/main.py, opencompass/configs/datasets/OlympiadBench/OlympiadBench_0shot_llmverify_gen_be8b13.py, opencompass/configs/datasets/aime2024/aime2024_llmverify_repeat16_gen_bf7475.py, opencompass/configs/datasets/aime2024/aime2024_llmverify_repeat8_gen_e8fcee.py, opencompass/configs/datasets/math/math_prm800k_500_llmverify_gen_6ff468.py, opencompass/configs/datasets/math/math_prm800k_500_llmverify_repeat4_gen_97b203.py, opencompass/configs/models/hf_internlm/lmdeploy_internlm3_8b_instruct.py, opencompass/datasets/base.py, opencompass/openicl/icl_retriever/icl_topk_retriever.py, requirements/runtime.txt, tools/list_configs.py
=> [Update] Support AIME-24 Evaluation for DeepSeek-R1 series

opencompass/datasets/TheoremQA/main.py, opencompass/openicl/icl_evaluator/icl_plugin_evaluator.py, requirements/runtime.txt
1. Upgrade sentence-transformers to be compatible with latest huggingface_hub 
2. Update TheoremQA and T-eval configs to be compatible with latest pass@k implementation
=> [Fix] Fix compatible issue

README.md, README_zh-CN.md, docs/en/index.rst, docs/en/user_guides/deepseek_r1.md, docs/zh_cn/index.rst, docs/zh_cn/user_guides/deepseek_r1.md, examples/eval_deepseek_r1.py, opencompass/configs/datasets/OlympiadBench/OlympiadBenchMath_0shot_llmverify_gen_9c22f2.py, opencompass/configs/datasets/OlympiadBench/OlympiadBench_categories.py, opencompass/configs/datasets/livemathbench/livemathbench_hard_custom_llmverify_gen_85d0ef.py, opencompass/configs/datasets/livemathbench/livemathbench_hard_custom_llmverify_gen_9e7505.py, opencompass/configs/datasets/omni_math/omni_math_llmverify_gen_ccf9c0.py, opencompass/configs/summarizers/groups/OlympiadBench.py, opencompass/datasets/generic.py, opencompass/datasets/livemathbench/livemathbench.py, opencompass/models/turbomind_with_tf_above_v4_33.py
=> [Update] Support OlympiadBench-Math/OmniMath/LiveMathBench-Hard

docs/en/user_guides/deepseek_r1.md
fix typo in deepseed_r1.md
docs/en/user_guides/deepseek_r1.md
**Before PR**:
**After PR**:
=> [Update] Fix typo in deepseed_r1.md

opencompass/configs/datasets/mmlu_pro/mmlu_pro_0shot_nocot_genericllmeval_gen_08c1de.py
1. Add generic LLM evaluation for MMLU Pro
=> [Update] Add generic LLM evaluation for MMLU Pro

opencompass/openicl/icl_evaluator/__init__.py, opencompass/openicl/icl_evaluator/math_evaluator.py
1. Fix import for Math Verifier
=> [Fix] Fix math-verify evaluator

opencompass/configs/datasets/aime2024/aime2024_llmjudge_gen_5e9f4f.py, opencompass/configs/datasets/aime2025/aime2025_llmjudge_gen_5e9f4f.py, opencompass/configs/datasets/bbeh/bbeh_llmjudge_gen_86c3a0.py, opencompass/configs/datasets/cmmlu/cmmlu_llmjudge_gen_e1cd9a.py, opencompass/configs/datasets/drop/drop_llmjudge_gen_3857b0.py, opencompass/configs/datasets/hellaswag/hellaswag_llmjudge_gen_809ef1.py, opencompass/configs/datasets/mmlu/mmlu_llmjudge_gen_f4336b.py, opencompass/configs/datasets/musr/musr_llmjudge_gen_b47fd3.py, opencompass/configs/datasets/supergpqa/supergpqa_llmjudge_gen_12b8bc.py, opencompass/datasets/livecodebench/pass_k_utils.py, opencompass/datasets/supergpqa/supergpqa.py, opencompass/tasks/openicl_eval.py
1. Add configurations for llmjudge of serveral datasets
2. Update Livecodebench return details 
3. Update openicl format details logic
=> [Update] Add configurations for llmjudge dataset

docs/en/advanced_guides/llm_judge.md, docs/zh_cn/advanced_guides/llm_judge.md, opencompass/configs/summarizers/groups/OlympiadBench.py, opencompass/evaluator/generic_llm_evaluator.py, opencompass/utils/run.py
=> Update OlympiadBench and Update LLM Judge

opencompass/models/openai_api.py
1. Unset disallowed_special token for Openai model
=> [Update] Unset disallowed_special token for Openai model

opencompass/runners/volc.py
1. Increase memory size for CPU job of VOLC Runner
=> [Update] Increase memory size for CPU job of VOLC Runner

opencompass/configs/datasets/korbench/korbench_llmjudge_gen_56cf43.py
1. Add Korbench  config with no max_out_len
=> [Update] Add Korbench  config with no max_out_len

opencompass/configs/datasets/aime2024/aime2024_llmjudge_gen_5e9f4f.py
=> [Bug] Aime2024 config fix

README.md, README_zh-CN.md, dataset-index.yml, docs/en/statis.py, docs/zh_cn/statis.py
=> [Doc]Add TBD Token in Datasets Statistics

opencompass/configs/models/intervl/lmdeploy_intervl_2_5_38b.py, opencompass/configs/models/intervl/lmdeploy_intervl_2_5_8b.py
1. Add model configs for intervl-8b & 38b, and use lmdeploy to test the LLM capabilities of vlm.
=> [Feature] Add Intervl-8b & 38b model config

opencompass/datasets/TheoremQA/number_utils.py, opencompass/datasets/TheoremQA/utils.py, opencompass/models/claude_sdk_api.py, opencompass/models/openai_api.py, requirements/extra.txt
1. Update requirements to fix conflict between datasets dependency
2. Add thinking mode to ClaudeSDK class
3. Update OpenaiSDK to handle empty response from server
=> [Update] Minor updates

opencompass/configs/datasets/math/math_prm800k_500_0shot_cot_gen_11c4b5.py, opencompass/configs/datasets/math/math_prm800k_500_gen.py
=> [Fix] Math-500 Config Setting

docs/en/conf.py, docs/zh_cn/conf.py
=> 【Doc Fix】404 ref between zh & en

.pre-commit-config-zh-cn.yaml, .pre-commit-config.yaml, dataset-index.yml, opencompass/configs/datasets/MedXpertQA/MedXpertQA_gen.py, opencompass/configs/datasets/MedXpertQA/MedXpertQA_llmjudge_gen.py, opencompass/datasets/MedXpertQA.py, opencompass/datasets/__init__.py
=> Add MedXpertQA

.github/scripts/oc_score_baseline_fullbench.yaml, .github/scripts/oc_score_baseline_testrange.yaml, .github/workflows/daily-run-test.yml, opencompass/datasets/subjective/__init__.py, opencompass/datasets/subjective/commonbench.py
=> [ci] update baseline for kernal change of vllm and lmdeploy

opencompass/openicl/icl_evaluator/icl_base_evaluator.py
=> [Fix] Fix compare error when k is list in base_evaluator

opencompass/datasets/generic.py
1. Handle case where LLM Judge not following output format, outputs like
=> [Feature] LLM Judge sanity check

opencompass/datasets/generic.py, opencompass/models/openai_api.py
1. Fix LLM Judge metrics cacluation
2. Update OpenAI SDK to concat reasoning content to output
=> [Update] Fix LLM Judge metrics cacluation

examples/eval_rewardbench.py, opencompass/configs/datasets/judge/rewardbench.py, opencompass/configs/summarizers/rewardbench.py, opencompass/datasets/__init__.py, opencompass/datasets/judge/__init__.py, opencompass/datasets/judge/rewardbench.py, opencompass/openicl/icl_evaluator/__init__.py, opencompass/openicl/icl_evaluator/icl_judge_evaluator.py
=> [Add] add rewardbench

opencompass/configs/datasets/ChemBench/ChemBench_llmjudge_gen_c584cf.py, opencompass/datasets/TheoremQA/utils.py, opencompass/datasets/judge/rewardbench.py, opencompass/datasets/smolinstruct.py
1. Fix ChemBench path Bug
2. Fix SMolInstruct import BUG
3. Update TheoremQA utils to be compatible with latest latex2sympy upgrade
=> [Update] Update dataset configs

opencompass/datasets/smolinstruct.py
=> [Bug] SMolInstrut safe meteor score

opencompass/datasets/smolinstruct.py
1. Fix SmolInsturct logger import
=> [Bug] Fix SmolInsturct logger import 

opencompass/datasets/base.py
=> [Fix] fix dataset repeat by concatenating

opencompass/models/openai_api.py
1. Return reasoning_content if content is empty
2. Concat reasoning content + think tag + content if all are non empty
=> [Update] OpenAI SDK model reasoning content 

dataset-index.yml, opencompass/configs/datasets/internsandbox/internsandbox_gen.py, opencompass/configs/datasets/internsandbox/internsandbox_gen_44b982.py, opencompass/datasets/__init__.py, opencompass/datasets/internsandbox.py
=> [Feature] Support InternSandbox 

opencompass/configs/datasets/mmlu_pro/mmlu_pro_biomed_0shot_cot_gen_057927.py, opencompass/configs/datasets/mmlu_pro/mmlu_pro_biomed_0shot_nocot_genericllmeval_gen_057927.py
=> MMLU_Pro Biomedical Version Support

opencompass/datasets/base.py
1. Set load_from_cache_file to False to avoid cache accmulation
=> [Update] Set load_from_cache_file to False

opencompass/configs/datasets/HLE/hle_biomed_llm_verify_gen_6ff468.py, opencompass/datasets/hle.py
=> HLE Biomedical version support

opencompass/models/openai_api.py
希望在 OpenAI 中新增 o4-mini，使得 o4-mini 可以正常评测。
在 O1_MODEL_LIST 中新增了 o4-mini 模型。
=> add o4-mini

opencompass/models/glm.py, opencompass/models/interntrain.py
=> [fix] use another way to avoid lint error

opencompass/datasets/srbench.py
1. Handle SRbench non-parseable pred
=> [Update] Handle SRbench non-parseable pred

opencompass/datasets/supergpqa/supergpqa.py, opencompass/evaluator/cascade_evaluator.py
=> [Dataset] Fix SuperGPQA postprocess

opencompass/configs/models/qwen3/lmdeploy_qwen3_0_6b.py
model list field is models not model
=> Fix qwen3 model config field error

opencompass/openicl/icl_inferencer/icl_base_inferencer.py
Reverts open-compass/opencompass#2074
=> [Revert] "BaseInferencer batch_size and max_seq_len cast to int"

opencompass/models/openai_api.py
=> Add new param. openai_extra_kwargs in OpenAISDK

opencompass/configs/datasets/codecompass/codecompass_gen_079a6c.py, opencompass/datasets/__init__.py, opencompass/datasets/codecompass/CodeCompass.py, opencompass/datasets/codecompass/__init__.py, opencompass/datasets/codecompass/codecompass_runner.py, opencompass/datasets/codecompass/evaluator.py, opencompass/datasets/codecompass/executor.py, opencompass/datasets/codecompass/metrics.py, opencompass/datasets/codecompass/utils.py
This PR introduces the CodeCompass Benchmark for Code Generation.
The implementation pulls data directly from the Hugging Face Hub.
The dataset configuration has been tested and validated to ensure correctness.
=> [Feature] Add CodeCompass dataset and configs #2199

opencompass/models/openai_api.py, opencompass/runners/rjob.py, opencompass/tasks/openicl_attack.py, opencompass/tasks/openicl_eval.py, opencompass/tasks/openicl_infer.py, opencompass/tasks/subjective_eval.py
=> torchrun -> sys.executable -m torch.distributed.run to avoid unexpected PATH environment 
