- opencompass/openicl/icl_retriever/icl_base_retriever.py
- opencompass/openicl/icl_retriever/icl_mdl_retriever.py
Fix the error caused by reordering the init statements:
```
│     7 import tqdm                                                            │                        
│     8 from transformers import AutoModelForCausalLM                          │                                                                                                                                                                       
│     9                                                                        │                         
│ ❱  10 from opencompass.openicl import PromptTemplate                         │                                                                                                                                                                       │    11 from …
```
> [Fix] Fix circular import of PromptTemplate

- docs/en/tools.md
- docs/zh_cn/tools.md
- opencompass/partitioners/size.py
- tools/prediction_merger.py
Inferencing on datasets like math / some subsets of bbh is extremely slow. Partition these datasets will relieve the inconvenience to some extent.
If the name of datasets matches some pattern, the size partition factor will be enlarged 10x.
Reuse of former `workdir` may cause wrong results, because of different size partition method.
> [Feature] Add heuristic size partitioner

- README.md
- README_zh-CN.md
- docs/en/get_started.md
- docs/zh_cn/get_started.md
> [Enhancement] Update README.md

- configs/datasets/siqa/siqa_gen_e78df3.py
- opencompass/datasets/siqa.py
- opencompass/openicl/icl_evaluator/icl_hf_evaluator.py
Prior to that, the only clue to determine whether the model made a right choice in multiple-choice questions is by strictly matching the leading capital character, which may underestimate the model's performance if the model tends to output the choice content instead of the leading character.
Now the model's choice can be matched to the one which has the minimum edit distance.
Addressing https://github.com/InternLM/opencompass/issues/52
> [Feature] Evaluating acc based on minimum edit distance, update SIQA

- opencompass/tasks/base.py
In debugging mode, the config objects are directly passed to Task instances, which may modify the fields inside and cause some unexpected errors in other processes that assume the sanity of the config.
Closing #171 
Use a copy of the config object in Task.
> [Fix] Use a copy of the config object in Task

- configs/datasets/agieval/agieval_gen_0a9ace.py
- configs/datasets/agieval/agieval_gen_397d81.py
- configs/datasets/agieval/agieval_mixed_2f14ad.py
- opencompass/datasets/agieval/agieval.py
Arise from https://github.com/InternLM/opencompass/issues/127 and https://github.com/InternLM/opencompass/issues/40
> [Fix] Fix AGIEval multiple choice

- configs/datasets/glm/humaneval.py
- configs/eval_gpt4.py
- opencompass/datasets/humaneval.py
- tests/dataset/test_humaneval.py
Enhance humaneval postprocessor so that it handles more corner cases. **This PR needs to be tested on other models thoroughly before being merged**.
Some models may wrap the result in the code block annotated with the language name.
````
```python
```
````
Some models may first repeat the question before generating the completion code.
```python
import xxx
def xxx():
```
> [Enhancement] Add humaneval postprocessor for GPT models & eval config for GPT4, enhance the original humaneval postprocessor

- opencompass/models/base.py
- tests/openicl/test_prompt_template.py
Correctly handle the case where the "begin" and "end" section contains the role with "generate=True".
> Fix meta template & unit tests

- README.md
- README_zh-CN.md
- docs/en/_static/js/custom.js
- docs/en/advanced_guides/evaluation_turbomind.md
- docs/en/index.rst
- docs/en/notes/contribution_guide.md
- docs/en/prompt/overview.md
- docs/zh_cn/_static/js/custom.js
- docs/zh_cn/advanced_guides/evaluation_turbomind.md
- docs/zh_cn/index.rst
- docs/zh_cn/notes/contribution_guide.md
- docs/zh_cn/prompt/overview.md
> [Docs] Update contribution guide & toc, improve user experience

- opencompass/tasks/mm_infer.py
Inference with --mm-eval arg leads to multiple rounds of running.
In slurm runner, the task reruns when job failure is detected, the related code is as below:
https://github.com/InternLM/opencompass/blob/4fc1701209adad832f7fca91640fac34331b8e29/opencompass/runners/slurm.py#L150-L152
And the output path is obtained by calling `task.get_output_paths()`:
https://github.com/InternLM/opencompass/blob/4fc1701209adad832f7fca91640fac34331b8e29/opencompass/runners/slurm.py#L129-L131
However, in `MultimodalInferTask`, the returned path of …
> [Fix] Fix bugs of multiple rounds of inference when using mm_eval

- configs/multimodal/minigpt_4/minigpt_4_7b_mme.py
- opencompass/metrics/__init__.py
- opencompass/metrics/mme_score.py
- opencompass/multimodal/datasets/__init__.py
- opencompass/multimodal/datasets/mmbench.py
- opencompass/multimodal/datasets/mme.py
- opencompass/multimodal/models/minigpt_4/__init__.py
- opencompass/multimodal/models/minigpt_4/post_processor.py
- opencompass/multimodal/models/minigpt_4/prompt_constructor.py
> [Feat] Support multi-modal evaluation on MME benchmark.

- opencompass/datasets/game24.py
as `sympy` is not in requirement.
> [Fix] use sympy only when necessary

- tools/case_analyzer.py
- tools/prediction_merger.py
- tools/prompt_viewer.py
Make descriptions of tools more relevant.
Updated argparse.ArgumentParser's description
**Before PR**:
**After PR**:
> [fixes] update descriptions of tools

- configs/eval_claude.py
- configs/eval_claude2.py
- configs/models/claude.py
- configs/models/claude2.py
- opencompass/models/__init__.py
- opencompass/models/claude_api/__init__.py
- opencompass/models/claude_api/claude_api.py
- opencompass/models/claude_api/postprocessors.py
- opencompass/tasks/openicl_eval.py
- opencompass/utils/build.py
- opencompass/utils/text_postprocessors.py
Different models have different output styles, sometimes it's hard to share a universal postprocessor across all the models, which may underestimate some outlier's performance.
This PR adds a `pred_postprocessor` parameter to `model`'s config, where users can customize postprocessors with respect to each datasets via a dataset_abbreviation -> postprocessor construction dict. The configuration from model side has the higher priority over the dataset-side.
None
> [Feature] Support model-bound prediction postprocessor, use it in Claude

- opencompass/openicl/icl_retriever/icl_zero_retriever.py
https://github.com/open-compass/opencompass/issues/338
> [Feature] Ignore ZeroRetriever error when id_list provided

- opencompass/runners/dlc.py
- opencompass/runners/local.py
- opencompass/runners/slurm.py
- opencompass/utils/run.py
- run.py
The former logic in run.py is rather complex when user chooses to specify task parameters from CLI instead of config - it uses "exec_xxx_runner" and makes the entire execution flow diverge from the configuration path. Such an implementation makes it hard for future maintenance and leads to unnecessary code redundancies.
This PR unifies the execution flow and now all the parameter specifications are performed through the modifications on the configuration object. 
Besides, this PR uses `try... finally...` to make sure temporary files created during running can be cleaned even when an exception has been raised (e.g. KeyBoardInterrupt).
> [Sync] [Enhancement] Simplify execution logic in run.py; use finally to clean up temp files

- opencompass/models/llama2.py
Avoid using the `text_completion` method to prevent the evaluation from crashing due to excessively long input token strings.
> [Feature] Update llama2 implement

- opencompass/openicl/icl_retriever/icl_mdl_retriever.py
Fix OOM while using MDLRetriever
wrap critical func with `torch.no_grad`
**Before PR**:
**After PR**:
> fix potential OOM issue

- opencompass/utils/run.py
- opencompass/utils/summarizer.py
- run.py
The new CLI mode is very helpful. But it's lack of custom summarizer argument. This PR solves this. User can use `python run.py --models hf_qwen_7b --datasets smoking_gen --summarizer configs/summarizers/medium.py` to run with custom summarizer. 
1. Add --summarizer argument
2. read related config file
3. fix related bug to compatible with command without custom summarizer
The following cases are tested. `smoking_gen` is a short custom defined dataset to test quickly.
- `python run.py --models hf_qwen_7b --datasets smoking_gen …
> feat: add custom summarizer argument in CLI run mode 在CLI启动模式中添加自定义Summarizer参数

- opencompass/utils/run.py
- run.py
If the config path can be customized, then when other projects introduce opencompass, they can maintain their own datasets/models configuration in their own projects:)
> support customize config path

- configs/datasets/wikitext/wikitext_103_raw_ppl.py
- configs/datasets/wikitext/wikitext_103_raw_ppl_752e2a.py
- configs/datasets/wikitext/wikitext_2_raw_ppl.py
- configs/datasets/wikitext/wikitext_2_raw_ppl_752e2a.py
Add text generation dataset WikiText.
Need to add a new PPLInferencer.
**Before PR**:
**After PR**:
> [SIG] add WikiText-2&103

- opencompass/openicl/icl_inferencer/icl_clp_inferencer.py
> [Fix] fix clp potential error and support bs>1

- configs/datasets/GLUE_CoLA/GULE_CoLA_ppl_77d0df.py
- configs/datasets/GLUE_QQP/GLUE_QQP_ppl_250d00.py
- configs/datasets/ceval/ceval_gen_2daf24.py
- configs/datasets/ceval/ceval_gen_5f30c7.py
- configs/datasets/ceval/ceval_ppl_578f8d.py
- configs/datasets/ceval/ceval_ppl_93e5ce.py
- configs/datasets/cmb/cmb_gen_72cbb7.py
- configs/datasets/cmmlu/cmmlu_gen_c13365.py
- configs/datasets/cmmlu/cmmlu_ppl_8b9c76.py
- configs/datasets/mmlu/mmlu_gen_23a9a9.py
- configs/datasets/mmlu/mmlu_gen_5d1409.py
- configs/datasets/mmlu/mmlu_gen_79e572.py
- configs/datasets/mmlu/mmlu_gen_a484b3.py
- configs/datasets/mmlu/mmlu_ppl_ac766d.py
- configs/datasets/nq/nq_gen_0356ec.py
- configs/datasets/triviaqa/triviaqa_gen_0356ec.py
- docs/en/prompt/prompt_template.md
- docs/zh_cn/prompt/prompt_template.md
- opencompass/openicl/icl_inferencer/icl_agent_inferencer.py
- opencompass/openicl/icl_inferencer/icl_attack_inferencer.py
- opencompass/openicl/icl_inferencer/icl_base_inferencer.py
- opencompass/openicl/icl_inferencer/icl_clp_inferencer.py
- opencompass/openicl/icl_inferencer/icl_gen_inferencer.py
- opencompass/openicl/icl_inferencer/icl_ppl_inferencer.py
- opencompass/openicl/icl_inferencer/icl_sc_inferencer.py
- opencompass/openicl/icl_inferencer/icl_tot_inferencer.py
- opencompass/openicl/icl_retriever/icl_fix_k_retriever.py
- opencompass/utils/prompt.py
- tools/prompt_viewer.py
- tools/update_dataset_suffix.py
The prior design that decoupled `fix_id_list` from `FixKRetriever` was terrible and resulted in code redundancy in Inferencers. It also hampered the development of some incoming features.
This PR breaks some custom config where `FixKRetriever` is used, but the effect may not be significant, and the migration cost is acceptable. Specifically, users would need to change their configs from
```python
xxx_infer_cfg = dict(
...
retriever=dict(type=FixKRetriever),
inferencer=dict(type=PPLInferencer, fix_id_list=[0, 1, 2, 3, 4]))
```
to 
```python
xxx_infer_cfg = dict(
...
retriever=dict(type=FixKRetriever, fix_id_list=[0, 1, 2, 3, 4])),
inferencer=dict(type=PPLInferencer)
```
Which is quite straightforward.
> [Refactor] Move fix_id_list to Retriever

- configs/datasets/lcsts/lcsts_gen_8ee1fe.py
- configs/datasets/lcsts/lcsts_gen_9b0b89.py
- docs/en/user_guides/metrics.md
- docs/zh_cn/user_guides/metrics.md
- opencompass/openicl/icl_evaluator/__init__.py
- opencompass/openicl/icl_evaluator/icl_hf_evaluator.py
- opencompass/openicl/icl_evaluator/icl_jieba_rouge_evaluator.py
- requirements/runtime.txt
The original rouge implementation used the one from huggingface, which could not handle Chinese datasets, such as LCSTS, correctly and would output 0. In the LCSTS dataset, there were English words and numbers. The huggingface rouge calculation would ignore all Chinese characters and only consider English words and numbers for scoring.
Now, we have switched to using jieba for tokenization and adopted the implementation from https://github.com/pltrdy/rouge, which can correctly process Chinese.
> [Fix] Use jieba rouge in lcsts

- opencompass/tasks/openicl_eval.py
Some models use `<eoa>` as end of assistant token in SFT, the original implementation causes the evaluation results to be unable to write `<`.
> [Fix] split if and only if complete eos string shows up

- opencompass/utils/run.py
In case of the following error, where summarizer is set to None
```text
Traceback (most recent call last):
File "/mnt/hwfile/zhoufengzhe/repos/prs/opencompass/run.py", line 329, in <module>
main()
File "/mnt/hwfile/zhoufengzhe/repos/prs/opencompass/run.py", line 322, in main
summarizer_cfg['type'] = DefaultSummarizer
TypeError: 'NoneType' object does not support item assignment
```
> [Fix] Fix summary default

- opencompass/models/__init__.py
- opencompass/models/zhipuai.py
- opencompass/runners/local_api.py
Our api only has `query_per_second` to restrict speed, to fulfill the the satisfaction of concurrent users when use a private key. Implement `LocalAPIRunner`.
Please use `LocalAPIRunner` in config and it only for api model infer.
`max_num_workers`, total number of subprocess.
`concurrent_users`, total number of concurrent user for online generation.
```
infer = dict(
partitioner=dict(type=NaivePartitioner),
runner=dict(
type=LocalAPIRunner,
max_num_workers=4,
concurrent_users=10,
task=dict(type=OpenICLInferTask)),
)
```
Model files should be modified correspondingly to suit this need.
One can refer to `ZhiPuAI` API model for reference …
> [Feat] local api speed up with fixed concurrent users

- opencompass/summarizers/multi_model.py
- requirements/runtime.txt
- tools/viz_multi_model.py
Added a new tool script that can visually compare the result of different models in the command line.
- a new tool script: viz_multi_model.py
- new dependency package in requirements/runtime.txt:
- [rich](https://github.com/Textualize/rich): for beautiful formatting in the terminal
- [typer](https://github.com/tiangolo/typer): make write cli tool easier
Model configurations and outputs that can be used for testing: [example_configs_and_outputs.zip](https://github.com/open-compass/opencompass/files/13184776/example_configs_and_outputs.zip)
**use case1**: show summarizer of different models, the script will check if the dataset of the model is consistent. 
```bash
python3 tools/viz_multi_model.py \
--cfg-paths ./configs/eval_model1.py \
--work-dirs ./outputs/model1/20231025_153230 \ …
```
> add multi model viz

- README.md
There we typo errors in the readme.md file
> Typo error in README.md

- configs/datasets/humanevalx/humanevalx_gen_0af626.py
- configs/datasets/humanevalx/humanevalx_gen_620cfa.py
- docs/en/advanced_guides/code_eval_service.md
- docs/zh_cn/advanced_guides/code_eval_service.md
> [Docs] add humanevalx dataset link in config

- opencompass/openicl/icl_inferencer/icl_attack_inferencer.py
- opencompass/openicl/icl_inferencer/icl_gen_inferencer.py
- opencompass/openicl/icl_inferencer/icl_sc_inferencer.py
- opencompass/openicl/icl_inferencer/icl_tot_inferencer.py
Use resume prediction as defaults for better experience
**Before PR**:
**After PR**:
> [Fix] change save_every defaults to 1

- configs/datasets/FinanceIQ/FinanceIQ_gen.py
- configs/datasets/FinanceIQ/FinanceIQ_gen_e0e6b5.py
- configs/datasets/FinanceIQ/FinanceIQ_ppl.py
- configs/datasets/FinanceIQ/FinanceIQ_ppl_42b9bd.py
- opencompass/datasets/FinanceIQ.py
- opencompass/datasets/__init__.py
Add FinanceIQ dataset for Chinese financial evaluations.
Create ``configs/datasets/FinanceIQ``
Create`` opencompass/datasets/FinanceIQ.py``  to load FinanceIQ dataset.
Modified the init files to load the classes.
Add FinanceIQ data files to OpenCompassData.zip. The dataset files can be found here: https://github.com/Duxiaoman-DI/XuanYuan/tree/main/FinanceIQ/data
> Add FinanceIQ dataset

- configs/datasets/MathBench/mathbench_gen.py
- configs/datasets/MathBench/mathbench_gen_ad37c1.py
- configs/summarizers/mathbench.py
- opencompass/datasets/mathbench.py
- opencompass/utils/text_postprocessors.py
> Mathbench update postprocess

- configs/datasets/humaneval_plus/humaneval_plus_gen.py
- configs/datasets/humaneval_plus/humaneval_plus_gen_8e312c.py
- opencompass/datasets/humaneval.py
**How to use**
```
git clone --recurse-submodules git@github.com:open-compass/human-eval.git
cd human-eval
pip install -e .
pip install -e evalplus
```
**Results**
mistral-7b-instruct-v0.1-hf pass@1: 28.04878048780488
> [Feature] Support the use of humaneval_plus.

- README.md
- README_zh-CN.md
- configs/models/accessory/accessory_llama2_7b.py
- configs/models/accessory/accessory_mixtral_8x7b.py
- configs/models/accessory/accessory_sphinx_v2_1k.py
- opencompass/models/__init__.py
- opencompass/models/accessory.py
Support the evaluation of [LLaMA2-Accessory](https://github.com/Alpha-VLLM/LLaMA2-Accessory) models
Add the `LLaMA2AccessoryModel` class, which wraps the original LLaMA2-Accessory models, to `opencompass/models/accessory.py`. Three model config examples are also given.
No
> [Feature] Support LLaMA2-Accessory

- configs/datasets/ARC_c/ARC_c_clean_ppl.py
- configs/datasets/hellaswag/hellaswag_clean_ppl.py
- configs/datasets/mmlu/mmlu_clean_ppl.py
- configs/eval_contamination.py
- configs/summarizers/contamination.py
- opencompass/datasets/arc.py
- opencompass/datasets/hellaswag.py
- opencompass/datasets/mmlu.py
This PR is to extend contamination analysis to MMLU, Hellaswag, and ARC_c.
Now OpenCompass should be able to conduct contamination analysis on **CEval, MMLU, Hellaswag, and ARC_c**.
In [Contamination Detector](https://github.com/liyucheng09/Contamination_Detector/releases/tag/v0.1.1rc), actually Winogrande and CommonsenseQA are also supported, but since they have very little comtaminated samples, I don't think it's necessary to add them in OpenCompass.
See the example results below:
```
dataset     version    mode    baichuan2-7b-base-hf    -                              -                                        qwen-7b-hf        -                              -                                        llama_30b_autogptq    -                              -
----------  ---------  ------ …
```
> Contamination analysis for MMLU, Hellaswag, and ARC_c

- configs/api_examples/eval_api_nanbeige.py
- opencompass/models/__init__.py
- opencompass/models/nanbeige_api.py
Add support for the Nanbeige API.
Add support for the Nanbeige API.
No.
see configs/api_examples/eval_api_nanbeige.py
**Before PR**:
**After PR**:
> [Feature] Add  support of Nanbeige API

- configs/datasets/cdme/cdme200k.py
- opencompass/datasets/cdme/cdme.py
provide a better post-processing for CDME test. 
Changes the CDME(Needle In A Haystack)-related config and evaluator to support better post-processing. 
**Before PR**:
**After PR**:
> Update cdme config and evaluator

- .github/scripts/oc_score_assert.py
- .github/scripts/oc_score_baseline.yaml
- .github/workflows/daily-run-test.yml
- .github/workflows/pr-run-test.yml
add daily test. can run more models and datasets. if the score is not null and between baseline * 0.97 and baseline * 1.03, return true. ps, use newest pytorch version
pr test does not create new conda, to improve stability.
> add daily test case

- opencompass/datasets/gsm8k.py
We found that the current answer extraction method of the GSM8k dataset is string matching, which presents certain issues. For example, when the model outputs "24.0" and the answer is "24", it will be judged as wrong. However, as GSM8k is a mathematical dataset, it should use numerical variables for comparison.
We have changed the method from string matching to numerical matching.
If so, please describe how it breaks the …
> [Fix] Fix error in gsm8k evaluator

- configs/eval_internlm_chat_lmdeploy_pytorch.py
- opencompass/models/__init__.py
- opencompass/models/lmdeploy_pytorch.py
Support eval models with lmdeploy pytorch engine.
- add eval config
- add `LmdeployPytorchModel`
None
**Before PR**:
**After PR**:
> Support lmdeploy pytorch engine

- opencompass/runners/local.py
get_command_template方法中为命令行前缀添加了CUDA_VISIBLE_DEVICES=或set CUDA_VISIBLE_DEVICES=。导致task.run()分支失效。 
---------
CUDA_VISIBLE_DEVICES= or set CUDA_VISIBLE_DEVICES= is added to the command line prefix in the get_command_template method. Causes the task.run() branch to fail.
> [Fix]Fixed the problem of never entering task.run() mode in local scheduling mode.

- configs/datasets/FinanceIQ/FinanceIQ_gen.py
- configs/datasets/FinanceIQ/FinanceIQ_ppl.py
This import should be `from .FinanceIQ_gen_e0e6b5 import financeIQ_datasets` instead of `FinanceIQ_datasets`.
https://github.com/open-compass/opencompass/blob/120bf8b3990e5e3c085683398edd5997b7d31005/configs/datasets/FinanceIQ/FinanceIQ_gen_e0e6b5.py#L36
> Fix FinanceIQ_datasets import error

- docs/en/get_started/installation.md
- docs/zh_cn/get_started/installation.md
修复文档中的命令：`find . -name "*.zip" -exec unzip "{}" \;` 执行后报错：`unzip:  cannot find or open , .zip or .ZIP.` 的问题
fix this problem
> fix doc problem

- configs/eval_internlm_chat_turbomind_tis.py
- opencompass/models/turbomind_tis.py
There are two issues for `turbomind_tis`:
1. The dataset `SuperGLUE_WSC_gen_6dc406` seems deprecated
2. The `get_token_len` method is missing in `TurboMindTisModel`, which will cause issue:
```
ine 203, in get_generation_prompt_list_from_retriever_indices
while len(ice_idx) > 0 and prompt_token_num > max_seq_len:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```
Because the method in `BaseModel` is empty, the `prompt_token_num` is None.
@lvhan028 pls help check
1. Change the dataset to `SuperGLUE_WSC_gen_7902a7`
2. Add the `get_token_len` method
> Fix running issues in turbomind_tis

- configs/eval_internlm_chat_lmdeploy_tis.py
- opencompass/models/__init__.py
- opencompass/models/lmdeploy_tis.py
Propose evaluation code for [LMDeploy TIS Python backend](https://github.com/InternLM/lmdeploy/tree/main/lmdeploy/serve/turbomind/triton_python_backend).
Add evaluation model and config files.
```
python run.py configs/eval_internlm_chat_lmdeploy_tis.py -w outputs
```
**Before PR**:
**After PR**:
> Add lmdeploy tis python backend model

- opencompass/models/lmdeploy_pytorch.py
- opencompass/models/turbomind.py
The output structure of LMDeploy engines in v0.4.0 (the latest version) is changed.
> adapt to lmdeploy v0.4.0

- configs/datasets/agieval/agieval_gen.py
- configs/datasets/agieval/agieval_gen_617738.py
- configs/datasets/agieval/agieval_gen_64afd3.py
- configs/datasets/agieval/agieval_mixed.py
- configs/datasets/agieval/agieval_mixed_0fa998.py
**Fix AGIEval chinese sets**: 'jec-qa-kd' and 'jec-qa-ca' are chinese datasets.
https://github.com/open-compass/opencompass/blob/3098d788455dc785e6830f8c69eb9d1010c0cce1/configs/datasets/agieval/agieval_gen_64afd3.py#L194-L197
```diff
agieval_chinese_sets = [
'gaokao-chinese',
'gaokao-english',
'gaokao-geography',
'gaokao-history',
'gaokao-biology',
'gaokao-chemistry',
'gaokao-physics',
'gaokao-mathqa',
'logiqa-zh',
'gaokao-mathcloze',
+    'jec-qa-kd',
+    'jec-qa-ca',
]
```
```
以下是一道中国司法考试基础知识题，请选择正确的答案。\n中国商务部决定对...辖权的法院起诉\nThe answer is 
```
```
以下是一道中国司法考试基础知识题，请选择正确的答案。\n中国商务部决定对...辖权的法院起诉\n答案是： 
```
> [Fix] Fix AGIEval chinese sets

- README.md
- README_zh-CN.md
- configs/models/mixtral/hf_mixtral_8x22b_instruct_v0_1.py
- configs/models/mixtral/hf_mixtral_8x22b_v0_1.py
- configs/models/qwen/hf_qwen1_5_moe_a2_7b.py
- configs/models/qwen/hf_qwen1_5_moe_a2_7b_chat.py
Adding the following model config files:
- mistralai/Mixtral-8x22B-v0.1
- mistralai/Mixtral-8x22B-Instruct-v0.1
- Qwen/Qwen1.5-MoE-A2.7B
- Qwen/Qwen1.5-MoE-A2.7B-Chat
> [Feature] Add Qwen1.5 MoE 7b and Mixtral 8x22b model configs

- opencompass/datasets/mbpp.py
ThreadPoolExecutor -> ProcessPoolExecutor as timeout signal interrupts between threads.
> [Fix] use ProcessPoolExecutor during mbpp eval

- .github/workflows/daily-run-test.yml
add protobuf because of error InternLM2Converter requires the protobuf library but it was not found in your environment.
> add dependency in daily test workflow

- configs/models/mistral/vllm_mistral_7b_instruct_v0_1.py
- configs/models/mistral/vllm_mistral_7b_instruct_v0_2.py
- configs/models/mistral/vllm_mixtral_8x7b_instruct_v0_1.py
- configs/models/others/vllm_orionstar_14b_longchat.py
- configs/models/qwen/vllm_qwen1_5_14b_chat.py
- configs/models/qwen/vllm_qwen1_5_72b_chat.py
- configs/models/qwen/vllm_qwen_14b_chat.py
- configs/models/qwen/vllm_qwen_72b_chat.py
- configs/models/vicuna/vllm_vicuna_13b_v15_16k.py
- configs/models/vicuna/vllm_vicuna_7b_v15_16k.py
- configs/models/wizardlm/vllm_wizardlm_13b_v1_2.py
- configs/models/wizardlm/vllm_wizardlm_70b_v1_0.py
- configs/models/wizardlm/vllm_wizardlm_7b_v1_0.py
- configs/models/zephyr/vllm_zephyr_7b_beta.py
`TypeError: VLLM.__init__() got an unexpected keyword argument 'end_str'`
```sh
File "/workspace/xusong/opencompass/opencompass/tasks/openicl_infer.py", line 162, in <module>
inferencer.run()
File "/workspace/xusong/opencompass/opencompass/tasks/openicl_infer.py", line 73, in run
self.model = build_model_from_cfg(model_cfg)
File "/workspace/xusong/opencompass/opencompass/utils/build.py", line 25, in build_model_from_cfg
return MODELS.build(model_cfg)
File "/usr/local/lib/python3.10/dist-packages/mmengine/registry/registry.py", line 570, in build
return self.build_func(cfg, *args, **kwargs, registry=self)
File "/usr/local/lib/python3.10/dist-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
obj = obj_cls(**args)  # type: ignore
TypeError: VLLM.__init__() got an …
```
> Fix VLLM argument error

- configs/datasets/math/math_gen_265cce.py
Upgrade default math pred_postprocessor from `math_postprocess` to `math_postprocess_v2`
As mentioned in [document](https://github.com/open-compass/opencompass/tree/main/configs/datasets/math#math), the default pred_postprocessor is `math_postprocess_v2` in both [`math_4shot_base_gen_db136b`](https://github.com/open-compass/opencompass/blob/main/configs/datasets/math/math_4shot_base_gen_db136b.py) and [`math_0shot_gen_393424`](https://github.com/open-compass/opencompass/blob/main/configs/datasets/math/math_0shot_gen_393424.py).
`math_postprocess_v2` is more robust than `math_postprocess`.
https://github.com/open-compass/opencompass/blob/1f9f728f2262a0bd0b9a942d0db4f36841444c77/opencompass/datasets/math.py#L158-L161
> Upgrade default math `pred_postprocessor`

- configs/datasets/inference_ppl/README.md
- configs/datasets/inference_ppl/inference_ppl.py
- configs/eval_inference_ppl.py
- opencompass/datasets/__init__.py
- opencompass/datasets/inference_ppl.py
- opencompass/models/base.py
- opencompass/models/huggingface_above_v4_33.py
- opencompass/openicl/icl_evaluator/__init__.py
- opencompass/openicl/icl_evaluator/icl_misc_evaluator.py
- opencompass/openicl/icl_inferencer/__init__.py
- opencompass/openicl/icl_inferencer/icl_inference_ppl_only_inferencer.py
- opencompass/openicl/icl_retriever/icl_base_retriever.py
Commit the inference ppl datasets
Commit the inference ppl datasets
**Before PR**:
**After PR**:
> commit inference ppl datasets

- configs/summarizers/example.py
- configs/summarizers/groups/longbench.py
1. `longbench_zh` and `longbench_en` are important metrics.
https://github.com/THUDM/LongBench/tree/main?tab=readme-ov-file#leaderboard
2.  `longbench_code-completion` was counted twice in `longbench` group.
- remove duplicated `longbench_code-completion`
- add `longbench_zh` and `longbench_en`
- Fix `longbench` calculation
**Before PR**:
**After PR**:
> Add `en` and `zh` groups to longbench summarizer; Fix longbench overall score

- configs/models/hf_internlm/lmdeploy_internlm2_5_7b_chat_1m.py
This PR updates the config file for the InternLM2.5-7B-Chat-1M model. The modifications ensure that the configuration is consistent with the parameters provided on the [official Hugging Face page](https://huggingface.co/internlm/internlm2_5-7b-chat-1m#:~:text=You%20can%20run%20batch%20inference%20locally%20with%20the%20following%20python%20code%3A).
> [Fix] Fix InternLM2.5-7B-Chat-1M config

- configs/datasets/rolebench/instruction_generalization_eng.py
- configs/datasets/rolebench/instruction_generalization_zh.py
- configs/datasets/rolebench/role_generalization_eng.py
- opencompass/configs/datasets/rolebench/instruction_generalization_eng.py
- opencompass/configs/datasets/rolebench/instruction_generalization_zh.py
- opencompass/configs/datasets/rolebench/role_generalization_eng.py
`instruction_generalization_eng`, `instruction_generalization_zh`, `role_generalization_eng` get the same abbr, which cause error in evaluation.
```
python run.py --models hf_llama_7b --datasets instruction_generalization_eng instruction_generalization_zh
```
> [Feature] Add abbr for rolebench dataset

- opencompass/tasks/openicl_infer.py
There is no need to use `torchrun` for single GPU inference. 
Besides, `python` runner is more friendly for debugging.
The debugging snippet is as follows
https://github.com/open-compass/opencompass/blob/889e7e11409d83fe312ecc7d7f0ed8861a84cc92/opencompass/runners/local.py#L116-L131
> [Feature] Switch to python runner for single GPU

- opencompass/openicl/icl_retriever/__init__.py
- opencompass/openicl/icl_retriever/icl_sliding_k_retriever.py
This PR aims to introduce a new Sliding Window Retriever for in-context learning. The goal is to enhance the flexibility and effectiveness of example retrieval in the OpenCompass framework, particularly for scenarios where context relevance varies with the position of test examples.
This PR introduces two main modifications:
1. Added a new file `icl_sliding_k_retriever.py` implementing the `SlidingWindowRetriever` class.
2. Updated `__init__.py` to include the new `SlidingWindowRetriever` in the package exports.
The `SlidingWindowRetriever` allows for dynamic selection of in-context examples based on a sliding window approach, which can be particularly useful for tasks where the relevance of context changes as we progress through the dataset.
This modification does not introduce any …
> Add icl_sliding_k_retriever.py and update __init__.py

- .github/workflows/link-check.yml
This pull request fixes the link-check workflow by resolving an issue where the `|` was mistakenly used for line breaks in the `ignore-url` patterns. The correct separator for line continuation is `\`. Additionally, the workflow now supports manual triggering with `workflow_dispatch`.
- Updated the `link-check` job to correctly install and run `linkchecker`.
- Fixed the `ignore-url` patterns by replacing `|` with `\` for correct line continuation in YAML.
- Added manual trigger capability with `workflow_dispatch`.
> [Fix] Fix link-check workflow by adjusting line breaks in URL ignore patterns

- opencompass/datasets/truthfulqa.py
- opencompass/models/huggingface_above_v4_33.py
This PR enables the users of `opencompass` to leverage the Ascend NPU for better performance in inferencing when GPU device is not available.
- OS: ubuntu 20.04
- NPU: Atlas 300T A2
- CANN: 8.0.RC2
- torch-npu: 2.1.0
- torch: 2.1.0
Note
To properly install CANN, see [[here](https://ascend.github.io/docs/sources/ascend/quick_install.html)](https://ascend.github.io/docs/sources/ascend/quick_install.html) for more details.
In addition, The version of `torch-npu` should match that of `torch`, see [[here](https://github.com/Ascend/pytorch)](https://github.com/Ascend/pytorch) for more details.
In the NPU environment, the script from the Quick Start tutorial is supposed to run on the NPU device, but it is running on the CPU device instead. The scripts and error is as follows:
**Scripts:** …
> Bugfix-NPU-Support

- configs/datasets/ruler/ruler_128k_gen.py
- configs/datasets/ruler/ruler_16k_gen.py
- configs/datasets/ruler/ruler_1m_gen.py
- configs/datasets/ruler/ruler_32k_gen.py
- configs/datasets/ruler/ruler_4k_gen.py
- configs/datasets/ruler/ruler_8k_gen.py
- configs/datasets/ruler/ruler_combined_gen.py
- opencompass/configs/datasets/ruler/ruler_128k_gen.py
- opencompass/configs/datasets/ruler/ruler_16k_gen.py
- opencompass/configs/datasets/ruler/ruler_1m_gen.py
- opencompass/configs/datasets/ruler/ruler_32k_gen.py
- opencompass/configs/datasets/ruler/ruler_4k_gen.py
- opencompass/configs/datasets/ruler/ruler_8k_gen.py
- opencompass/configs/datasets/ruler/ruler_combined_gen.py
We need to ensure that we don't import anything that ends with "_datasets", or they will be picked up by the runner, leading to duplicate / unwanted datasets being evaluated. In this case, 4k datasets are always imported and evaluated, regardless of whether the user specifies other lengths.
Do not import duplicate `_datasets` from base config.
> Fix RULER datasets

- configs/datasets/ruler/ruler_16k_gen.py
- configs/eval_ruler.py
- opencompass/configs/datasets/ruler/ruler_16k_gen.py
https://github.com/open-compass/opencompass/pull/1628 fixed the RULER dataset loading but missed the change in `ruler_16k_gen.py` (oops). This PR fixes the issue.
Tested:
* `python run.py configs/eval_ruler.py`
* `opencompass --datasets ruler_16k_gen --hf-type base --hf-path facebook/opt-125m`
> Fix ruler_16k_gen

- README.md
- opencompass/utils/text_postprocessors.py
```
def first_option_postprocess(text: str, options: str, cushion=True) -> str:
"""Find first valid option for text."""
patterns = [
f'答案是?\s*([{options}])',
f'答案是?\s*：\s*([{options}])',
f'答案是?\s*:\s*([{options}])',
f'答案选项应?该?是\s*([{options}])',
f'答案选项应?该?为\s*([{options}])',
f'答案应该?是\s*([{options}])',
f'答案应该?选\s*([{options}])',
f'答案选项为?\s*：\s*([{options}])',
f'答案选项为?\s+\(?\*?\*?([{options}])\*?\*?\)?',
f'答案选项是?\s*:\s*([{options}])',
f'答案为\s*([{options}])',
f'答案选\s*([{options}])',
f'选择?\s*([{options}])',
f'故选?\s*([{options}])'
f'只有选?项?\s?([{options}])\s?是?对',
f'只有选?项?\s?([{options}])\s?是?错',
f'只有选?项?\s?([{options}])\s?不?正确',
f'只有选?项?\s?([{options}])\s?错误',
f'说法不?对选?项?的?是\s?([{options}])',
f'说法不?正确选?项?的?是\s?([{options}])',
f'说法错误选?项?的?是\s?([{options}])',
f'([{options}])\s?是正确的', …
```
> [Fix] Fix bug for first_option_postprocess

- opencompass/runners/volc.py
Update volc CPU flavor. Use `ml.c3i.2xlarge` instead of  `ml.c1ie.2xlarge`.
> [Update] update volc CPU flavor

- configs/datasets/livecodebench/livecodebench_gen.py
- configs/datasets/livecodebench/livecodebench_gen_6966bc.py
- opencompass/configs/datasets/livecodebench/livecodebench_gen.py
- opencompass/configs/datasets/livecodebench/livecodebench_gen_6966bc.py
- opencompass/configs/models/chatglm/lmdeploy_glm4_9b.py
- opencompass/configs/models/qwen2_5/lmdeploy_qwen2_5_14b.py
- opencompass/configs/models/qwen2_5/lmdeploy_qwen2_5_32b.py
- opencompass/configs/models/qwen2_5/lmdeploy_qwen2_5_72b.py
- opencompass/configs/models/yi/lmdeploy_yi_1_5_9b.py
- opencompass/models/openai_api.py
- opencompass/models/turbomind_with_tf_above_v4_33.py
1. Add error handler for Openai SDK (i.e. for models like step-2)
2. Update LCB configurations, add fallback_role in case of API models
3. Add some base models configuration
4. Update `TurboMindModelwithChatTemplate`, making sure the `max_out_len` has higher priority than `max_new_tokens` in `gen_config`
> [Update] Update configurations

- configs/api_examples/eval_api_bailing.py
- configs/models/bailing_api/bailing-lite-1116.py
- configs/models/bailing_api/bailing-pro-1120.py
- opencompass/configs/models/bailing_api/bailing-lite-1116.py
- opencompass/configs/models/bailing_api/bailing-pro-1120.py
- opencompass/models/bailing_api_oc.py
This PR makes the same sequence with input sample under the multiple samples.
construct the result list in advance then set the result of each sample in-place.
If so, please describe how it breaks the compatibility and how the downstream projects should modify their …
> [fix] output sequence under the multiple samples

- configs/datasets/subjective/wildbench/wildbench_pair_judge.py
- configs/datasets/subjective/wildbench/wildbench_pair_judge_new.py
- opencompass/configs/datasets/IFEval/IFEval_gen_353ae7.py
- opencompass/configs/datasets/humaneval/humaneval_openai_sample_evals_gen_dcae0e.py
- opencompass/configs/datasets/humanevalx/humanevalx_gen_3d84a3.py
- opencompass/configs/datasets/math/math_0shot_gen_11c4b5.py
- opencompass/configs/datasets/subjective/wildbench/wildbench_pair_judge.py
- opencompass/configs/datasets/subjective/wildbench/wildbench_pair_judge_new.py
1. Add dataset configuration with no max_out_len restrictions
2. Remove subjective wildbench max_out_len
> [Update] Update dataset configurations with no max_out_len

- .gitignore
- configs/datasets/subjective/compass_arena_subjective_bench/README_pairwise_bt.md
- configs/datasets/subjective/compass_arena_subjective_bench/multiturn/pairwise_bt_judge.py
- configs/datasets/subjective/compass_arena_subjective_bench/multiturn/pairwise_judge.py
- configs/datasets/subjective/compass_arena_subjective_bench/singleturn/pairwise_bt_judge.py
- configs/datasets/subjective/compass_arena_subjective_bench/singleturn/pairwise_judge.py
- configs/eval_compassarena_subjectivebench_bradleyterry.py
- opencompass/configs/datasets/subjective/compass_arena_subjective_bench/README_pairwise_bt.md
- opencompass/configs/datasets/subjective/compass_arena_subjective_bench/multiturn/pairwise_bt_judge.py
- opencompass/configs/datasets/subjective/compass_arena_subjective_bench/multiturn/pairwise_judge.py
- opencompass/configs/datasets/subjective/compass_arena_subjective_bench/singleturn/pairwise_bt_judge.py
- opencompass/configs/datasets/subjective/compass_arena_subjective_bench/singleturn/pairwise_judge.py
- opencompass/datasets/subjective/compass_arena_subjective_bench.py
- opencompass/datasets/subjective/utils.py
- opencompass/openicl/icl_evaluator/lm_evaluator.py
- opencompass/summarizers/subjective/__init__.py
- opencompass/summarizers/subjective/compass_arena_bradley_terry.py
Adapt the Bradley-Terry rating system from FastChat to the subjective evaluation setting, but replacing human evaluators with LLM-as-a-judge.
- Added the Bradley-Terry rating method for subjective evaluation. 
- Added `pairwise_bt_judge` for both singleturn and multiturn evaluation for compass_arena_subjective_bench.
- Added the `keep_preds` argument to the init method of `LMEvaluator` for an option to keep LLM predictions (from the inference stage) when saving judge responses during the evaluation stage. This is useful when the postprocessor needs to calculate metadata or metrics based on each LLM's predictions (e.g. response length).
- Added a step at the end of `CompassArenaBradleyTerrySummarizer.summarize` to fit another BT model with the first base_model and combining matches from …
> [Feature] Added CompassArena-SubjectiveBench with Bradley-Terry Model

- opencompass/configs/models/deepseek/lmdeploy_deepseek_v2_5_1210.py
- requirements/runtime.txt
1. Fix httpx version (requireded by BigCodebench)
2. Update Deepseek V2.5 default backend
> [Update] Update requirement and deepseek configurations

- opencompass/models/openai_api.py
- opencompass/runners/local.py
When multiple tasks are submitted in the cloud server's shared file system, the existing local_runner's logic for saving params.py files can cause conflicts between different tasks (these tasks may have the same pid).
Modify the save path of params.py to work dir of each task.
**Before PR**:
> [Fix] Fix Local Runner Params Save Path

- configs/datasets/ruler/ruler_128k_gen.py
- configs/datasets/ruler/ruler_16k_gen.py
- configs/datasets/ruler/ruler_1m_gen.py
- configs/datasets/ruler/ruler_32k_gen.py
- configs/datasets/ruler/ruler_4k_gen.py
- configs/datasets/ruler/ruler_64k_gen.py
- configs/datasets/ruler/ruler_8k_gen.py
- configs/datasets/ruler/ruler_niah_gen.py
- opencompass/configs/datasets/ruler/ruler_128k_gen.py
- opencompass/configs/datasets/ruler/ruler_16k_gen.py
- opencompass/configs/datasets/ruler/ruler_1m_gen.py
- opencompass/configs/datasets/ruler/ruler_32k_gen.py
- opencompass/configs/datasets/ruler/ruler_4k_gen.py
- opencompass/configs/datasets/ruler/ruler_64k_gen.py
- opencompass/configs/datasets/ruler/ruler_8k_gen.py
- opencompass/configs/datasets/ruler/ruler_niah_gen.py
- requirements/runtime.txt
Adding an optional environment variable `TOKENIZER_MODEL` which controls the tokenizer model to use for RULER data generation. With this option, the dataset length will be more precise when we evaluate models that do not use `gpt-4` tokenizer.
> Customizable tokenizer for RULER

- opencompass/configs/datasets/aime2024/aime2024_0shot_nocot_genericllmeval_gen_2b9dc2.py
- opencompass/configs/datasets/cmmlu/cmmlu_stem_0shot_nocot_gen_3653db.py
- opencompass/configs/datasets/gpqa/gpqa_0shot_nocot_genericllmeval_gen_772ea0.py
- opencompass/configs/datasets/korbench/korbench_single_0shot_genericllmeval_gen_17854d.py
- opencompass/configs/datasets/livemathbench/livemathbench_gen_6eb711.py
- opencompass/configs/datasets/livereasonbench/livereasonbench_genericllmeval_gen_f990de.py
- opencompass/configs/datasets/math/math_prm800k_500_0shot_nocot_genericllmeval_gen_63a000.py
- opencompass/configs/datasets/mmlu/mmlu_stem_0shot_gen_216503.py
- opencompass/evaluator/__init__.py
- opencompass/evaluator/generic_llm_evaluator.py
- opencompass/summarizers/default_subjective.py
- opencompass/tasks/subjective_eval.py
> [Feature] Update o1 evaluation with JudgeLLM

- configs/datasets/subjective/alpaca_eval/alpacav2_judgeby_gpt4_bradleyterry.py
- configs/datasets/subjective/compassarena/compassarena_compare_bradleyterry.py
- configs/datasets/subjective/wildbench/wildbench_pair_judge_bradleyterry.py
- configs/eval_subjective_bradleyterry.py
- opencompass/configs/datasets/subjective/alpaca_eval/alpacav2_judgeby_gpt4_bradleyterry.py
- opencompass/configs/datasets/subjective/compassarena/compassarena_compare_bradleyterry.py
- opencompass/configs/datasets/subjective/wildbench/wildbench_pair_judge_bradleyterry.py
- opencompass/datasets/subjective/__init__.py
- opencompass/datasets/subjective/alpacaeval.py
- opencompass/datasets/subjective/compass_arena.py
- opencompass/datasets/subjective/wildbench.py
- opencompass/openicl/icl_evaluator/lm_evaluator.py
- opencompass/summarizers/subjective/compass_arena_bradley_terry.py
Added Bradley-Terry subjective evaluation method to wildbench, alpacaeval, and compassarena datasets.
- Added Bradley-Terry subjective evaluation method to wildbench, alpacaeval, and compassarena datasets.
- Added `base_models_abbrs` (from dataset config) to references during subjective evaluation (passed to references in `LMEvaluator`). This can be used to determine the base models in the post-processor function for pairwise subjective comparisons.
- Added support for `base_models` in regular (non-Bradley-Terry) subjective evaluation post-processors for the following datasets: wildbench, alpacaeval, compassarena. Previously, the base model for comparison is assumed to be `answer1` in the first record of references (`references[0]["answer1"]`), but this might not necessarily hold if …
> [Feature] Added Bradley-Terry subjective evaluation method to wildbench, alpacaeval, and compassarena datasets

- configs/eval_compassarena_subjectivebench_bradleyterry.py
- configs/eval_subjective_bradleyterry.py
- opencompass/summarizers/subjective/compass_arena_bradley_terry.py
Added an option to report the predicted win rates instead of ELO scale ratings in `CompassArenaBradleyTerrySummarizer`
- Added an option to report the predicted win rates (win probabilities against the baseline model) instead of the ELO scale ratings.
- `report_pred_win_rates` is set to `True` by default, which reports the predicted win rates for downstream processes (what's being returned by the `summarize` method).
- Both predicted win rates and ELO scale ratings will be saved in the summary files regardless of whether `report_pred_win_rates` is turned on. This parameter only affects what's being returned by the `summarize` method.
`CompassArenaBradleyTerrySummarizer` now defaults to reporting the predicted win rates instead of the ELO scale ratings that were previously reported. You …
> [Feature] Added Predicted Win Probabilities to `CompassArenaBradleyTerrySummarizer`

- docs/en/get_started/installation.md
Rectified mistakes in the installation.md file
Updated installation commands
**Before PR**:
**After PR**:
> installation.md update

- opencompass/models/openai_api.py
1. Update max_out_len logic for OpenAI model
> [Fix] Update max_out_len logic for OpenAI model

- opencompass/datasets/LCBench.py
- opencompass/datasets/bigcodebench/bigcodebench.py
1. Modify the Evaluator of BigCodeBench;
2. Modify the load of LCBench.
> BigCodeBench & LCBench update

- opencompass/utils/run.py
When evaluating the model using OpenCompass with the vLLM accelerator, I encountered an "Out of Memory" error at startup. To address this, I attempted to control GPU memory usage by adding the `gpu_memory_utilization` parameter to the `model_kwargs` configuration. However, this adjustment did not take effect.  
Upon debugging, I discovered that in the `opencompass/opencompass/utils/run.py` file, the following line of code:  
```python
model_kwargs = dict(tensor_parallel_size=model['run_cfg']['num_gpus'], …
```
> fix the bug that model_kwargs passed in is invalid when the accelerator is vllm

- opencompass/configs/datasets/supergpqa/supergpqa_llmjudge_gen_12b8bc.py
- opencompass/datasets/supergpqa/supergpqa.py
- opencompass/evaluator/generic_llm_evaluator.py
- opencompass/openicl/icl_evaluator/icl_base_evaluator.py
1. Add SuperGPQA subset metrics
> [Update] SuperGPQA subset metrics

- .github/scripts/oc_score_baseline_fullbench.yaml
- .github/workflows/daily-run-test.yml
- .github/workflows/pr-run-test.yml
> [ci] Fix baseline score

- docs/en/user_guides/experimentation.md
- docs/zh_cn/user_guides/experimentation.md
- opencompass/cli/main.py
python script.py → dump_eval_details = True 
python script.py --dump-eval-details → dump_eval_details = True
python script.py --dump-eval-details False → dump_eval_details = False
python script.py --dump-eval-details false → dump_eval_details = False
> [Feature] Make dump-eval-details default behavior

- opencompass/datasets/subjective/arena_hard.py
> [fix] fix order bug Update arena_hard.py

- opencompass/models/openai_api.py
1. Concat OpenaiSDK reasoning content
> [Bug] Concat OpenaiSDK reasoning content

- opencompass/datasets/lawbench/utils/modules/alignment.py
- opencompass/datasets/lawbench/utils/modules/classifier.py
- An error occurred during the LawBench evaluation run.
- use `COMPASS_DATA_CACHE` path instead of relative path.
**Before PR**:
**After PR**:
> Fix lawbench evaluation

- opencompass/configs/models/gemma/vllm_gemma_3_12b_it.py
- opencompass/configs/models/gemma/vllm_gemma_3_27b_it.py
- opencompass/configs/models/gemma/vllm_gemma_3_4b_it.py
- opencompass/configs/models/hf_internlm/lmdeploy_internlm3_8b_instruct_128k.py
- opencompass/configs/models/hf_internlm/lmdeploy_oreal_32b.py
- opencompass/configs/models/qwen2_5/vllm_qwen2_5_14b_instruct_128k.py
- opencompass/configs/models/qwen2_5/vllm_qwen2_5_32b_instruct_128k.py
- opencompass/configs/models/qwen2_5/vllm_qwen2_5_72b_instruct_128k.py
- opencompass/configs/models/qwen2_5/vllm_qwen2_5_7b_instruct_128k.py
**Description:**  
- Add VLLM configs for Qwen2.5 models (7B/14B/32B/72B) supporting 128k long context.  
- Add VLLM configs for Gemma models (3-4B/12B/27B) with 128k context support.  
- Add TurboMind config for [OREAL-32B](https://github.com/InternLM/OREAL).
> [Update] Add Long-Context configs for Gemma, OREAL, and Qwen2.5 models

- .github/scripts/eval_regression_chat_sub_fullbench.py
- .github/scripts/oc_score_baseline.yaml
- .github/scripts/oc_score_baseline_fullbench.yaml
- .github/scripts/oc_score_baseline_testrange.yaml
- .github/workflows/daily-run-test.yml
> [ci] update baseline and fix lmdeploy version

- .pre-commit-config-zh-cn.yaml
- .pre-commit-config.yaml
- opencompass/models/glm.py
- opencompass/models/interntrain.py
> [CI] add check rule

- opencompass/configs/datasets/PHYBench/phybench_gen.py
- opencompass/datasets/phybench/box_extract.py
- opencompass/datasets/phybench/phybench.py
Motivation
This PR fixes a scoring bug in the phybench evaluation. The current implementation had an error in how scores were computed or aggregated, leading to incorrect evaluation results. The goal is to ensure that the benchmark results are accurate and consistent with the expected logic of the task.
Modification
Fixed the scoring logic in the phybench benchmark.
Adjusted the evaluation script to correctly calculate the metrics.
> Fix PHYbench

- opencompass/models/openai_api.py
- opencompass/runners/rjob.py
There is a bug while using rjob to submit task: misconsidering the Starting status of rjob 
take Starting status into consideration in rjob status loop
**Before PR**: …
> debug rjob runner
